;;; emmet2-corfu-test.el --- Optional Corfu display contracts -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-capf-test)
(require 'emmet2-corfu)

(ert-deftest emmet2-corfu-label-column-preserves-choice-and-undo ()
  (emmet2-test--with-css-completion "ta"
    (let ((corfu-max-width 12) shown)
      (cl-letf (((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (= (nth 1 shown) 0))
        (should (<= (nth 2 shown) 12))
        (dolist (line (nth 3 shown))
          (should (<= (string-width line) 12)))
        (should (seq-some (lambda (line) (string-suffix-p "…" line)) (nth 3 shown)))
        (let* ((candidates (copy-sequence corfu--candidates))
               (rows (cdr (corfu--affixate candidates)))
               (index (cl-position "text-align: center;" (mapcar #'cadr rows) :test #'equal)))
          (should (numberp index))
          (corfu--goto index)
          (corfu--exhibit)
          (should (equal-including-properties candidates corfu--candidates))
          (should (cl-every (lambda (candidate) (equal candidate "ta")) candidates))
          (corfu-insert)
          (should (equal (buffer-string) ".a{text-align: center;}"))
          (undo-only 1)
          (should (equal (buffer-string) ".a{ta}")))))))

(ert-deftest emmet2-corfu-rows-stay-plain-text-with-margin-formatters ()
  (emmet2-test--with-css-completion "ta"
    (let ((corfu-max-width 40)
          (corfu-margin-formatters (list (lambda (_metadata) (lambda (_candidate) "[I] "))))
          shown)
      (cl-letf (((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (= (nth 1 shown) 0))
        (should (member "text-align: center;" (mapcar #'substring-no-properties (nth 3 shown))))
        (should-not (seq-some (lambda (line) (string-search "[I]" line)) (nth 3 shown)))))))

(ert-deftest emmet2-corfu-anchor-refresh-and-new-session ()
  (emmet2-test--with-css-completion "ta"
    (let ((start (point)) shown)
      (cl-letf (((symbol-function 'posn-at-point)
                 (lambda (&optional position _window) (list (or position (point)))))
                ((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (equal (car shown) (list start)))
        (insert "c")
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should completion-in-region-mode)
        (should (equal (car shown) (list start)))
        (corfu-quit)
        (corfu-auto--complete-deferred)
        (should (equal (car shown) (list (1+ start))))))))

(ert-deftest emmet2-corfu-display-honors-frame-width-and-unicode ()
  (let* ((label (propertize "界😀long-label" 'face 'completions-common-part))
         (candidate (propertize "abbr" 'emmet2--choice 'identity))
         (rows (list (list candidate label "")))
         (corfu--metadata '(metadata (category . emmet2)))
         (completion-in-region--data '(nil nil nil nil nil))
         (corfu-max-width 100))
    (cl-letf (((symbol-function 'frame-width) (lambda (&optional _) 10)))
      (let ((text (caar (car (emmet2-corfu--rows (list rows))))))
        (should (<= (string-width text) 6))
        (should (string-suffix-p "…" text))
        (should (eq (get-text-property 0 'face text) 'completions-common-part))
        (should (eq (get-text-property 0 'emmet2--choice candidate) 'identity))
        (should (equal label "界😀long-label"))))))

(ert-deftest emmet2-corfu-other-categories-pass-through ()
  (let* ((arguments (list '(("name" "prefix" "suffix"))))
         (corfu--metadata '(metadata (category . eglot)))
         (completion-in-region--data '(nil nil nil nil (:other-property t)))
         (properties (nth 4 completion-in-region--data)))
    (should (eq (emmet2-corfu--rows arguments) arguments))
    (cl-letf (((symbol-function 'posn-at-point)
               (lambda (&rest _) (ert-fail "Foreign completion must keep its position"))))
      (should (eq (emmet2-corfu--anchor #'identity 'original-position) 'original-position)))
    (should (eq (nth 4 completion-in-region--data) properties))
    (should-not (plist-member properties :emmet2-corfu-anchor))))

(ert-deftest emmet2-corfu-installation-and-unload ()
  (let ((compiled (byte-code-function-p (symbol-function 'emmet2-corfu--rows))))
    (unwind-protect
        (progn
          (dotimes (_ 3) (emmet2-corfu--enable))
          (dolist (entry '((corfu--format-candidates . emmet2-corfu--rows)
                           (corfu--candidates-popup . emmet2-corfu--anchor)))
            (let ((count 0))
              (advice-mapc (lambda (function _properties)
                             (when (eq function (cdr entry)) (cl-incf count))) (car entry))
              (should (= count 1))))
          ;; Advice added afterwards keeps its position on later enables.
          (let ((outer (lambda (arguments) arguments)))
            (advice-add 'corfu--format-candidates :filter-args outer)
            (emmet2-corfu--enable)
            (let (order)
              (advice-mapc (lambda (function _properties) (push function order))
                           'corfu--format-candidates)
              (should (eq (car (last order)) outer)))
            (advice-remove 'corfu--format-candidates outer))
          (emmet2-mode-unload-function)
          (should-not (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (should-not (advice-member-p #'emmet2-corfu--anchor 'corfu--candidates-popup))
          ;; Independent hosts may keep using CAPF after the minor mode unloads.
          (with-temp-buffer
            (css-mode) (insert ".a{ta}") (backward-char)
            (should (emmet2-capf)))
          (should (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (unload-feature 'emmet2-corfu t)
          (should-not (advice-member-p 'emmet2-corfu--rows 'corfu--format-candidates))
          (should-not (advice-member-p 'emmet2-corfu--anchor 'corfu--candidates-popup))
          (with-temp-buffer
            (css-mode) (insert ".a{ta}") (backward-char)
            (should (emmet2-capf)))
          (should (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (should (eq compiled (byte-code-function-p (symbol-function 'emmet2-corfu--rows)))))
      (require 'emmet2-corfu)
      (emmet2-corfu--enable))))

(provide 'emmet2-corfu-test)
;;; emmet2-corfu-test.el ends here
