;;; emmet2-preview-test.el --- Preview ownership and integration -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-capf-contract-test)
(require 'emmet2-preview)
(require 'corfu-popupinfo)
(require 'typescript-ts-mode)

(ert-deftest emmet2-preview-three-buffers-exact-text-and-fontification ()
  (emmet2-preview-clear)
  (unwind-protect
      (with-temp-buffer
        (insert "source")
        (let ((tick (buffer-chars-modified-tick)) (source (current-buffer))
              (cases '((html html-mode "<main class=\"card\">界😀</main>")
                       (jsx js-jsx-mode "<main className={css.card}>界😀</main>")
                       (css css-mode "margin: 10px;\ncolor: #fff;"))))
          (dolist (case cases)
            (let* ((text (nth 2 case)) (buffer (emmet2-preview text (car case))))
              (should (eq buffer (emmet2-preview text (car case))))
              (with-current-buffer buffer
                (should (eq major-mode (cadr case)))
                (should (equal (buffer-substring-no-properties (point-min) (point-max)) text))
                (should (text-property-not-all (point-min) (point-max) 'face nil))
                (should (= (point) (point-min)))
                (should buffer-read-only)
                (should (eq buffer-undo-list t))
                (should-not (buffer-modified-p))
                (should-not buffer-file-name))))
          (should (= (length emmet2-preview--buffers) 3))
          (dotimes (_ 10)
            (dolist (case cases)
              (let ((buffer (emmet2-preview "" (car case))))
                (should (string-empty-p (with-current-buffer buffer (buffer-string))))
                (should (eq buffer (emmet2-preview (nth 2 case) (car case)))))))
          (should (= (length emmet2-preview--buffers) 3))
          (should (eq (current-buffer) source))
          (should (equal (buffer-string) "source"))
          (should (= (point) 7))
          (should (= tick (buffer-chars-modified-tick)))))
    (emmet2-preview-clear)))

(ert-deftest emmet2-preview-isolates-mode-hooks ()
  (emmet2-preview-clear)
  (let* ((trap (list (lambda () (ert-fail "Preview must not run user mode hooks"))))
         (change-major-mode-hook trap) (change-major-mode-after-body-hook trap)
         (after-change-major-mode-hook trap)
         (prog-mode-hook trap) (text-mode-hook trap) (sgml-mode-hook trap)
         (html-mode-hook trap) (js-mode-hook trap) (js-jsx-mode-hook trap) (css-mode-hook trap))
    (unwind-protect
        (dolist (syntax '(html jsx css))
          (with-current-buffer (emmet2-preview "test" syntax)
            (should-not delayed-mode-hooks)
            (should-not delayed-after-hook-functions)
            (should-not emmet2-mode)
            (should-not (memq #'emmet2-capf completion-at-point-functions))))
      (emmet2-preview-clear))))

(ert-deftest emmet2-preview-deletion-rebuild-and-unload ()
  (emmet2-preview-clear)
  (let ((unrelated (generate-new-buffer " *emmet2-unrelated-test*")))
    (unwind-protect
        (progn
          (let ((first (emmet2-preview "<p/>" 'html)))
            (kill-buffer first)
            (let ((second (emmet2-preview "<p/>" 'html)))
              (should (buffer-live-p second)) (should-not (eq first second))
              (should (= (length emmet2-preview--buffers) 1))))
          (let ((buffers (mapcar (lambda (syntax) (emmet2-preview "text" syntax)) '(html jsx css))))
            (dolist (buffer buffers)
              (with-current-buffer buffer (setq-local kill-buffer-query-functions '(ignore))))
            (emmet2-mode-unload-function)
            (should-not emmet2-preview--buffers)
            (should-not (seq-some #'buffer-live-p buffers)))
          (let ((buffer (emmet2-preview "color: red;" 'css)))
            (emmet2-preview-unload-function)
            (should-not (buffer-live-p buffer)))
          (should (buffer-live-p unrelated)))
      (emmet2-preview-clear)
      (kill-buffer unrelated))))

(ert-deftest emmet2-preview-initialization-failure-does-not-leak ()
  (emmet2-preview-clear)
  (let ((before (buffer-list)))
    (cl-letf (((symbol-function 'html-mode) (lambda () (error "Initialization failed"))))
      (should-error (emmet2-preview "<p/>" 'html)))
    (should-not emmet2-preview--buffers)
    (should (equal (buffer-list) before))
    (should-error (emmet2-preview "text" 'unsupported))
    (should (equal (buffer-list) before))))

(ert-deftest emmet2-preview-capf-shares-final-result-and-syntax ()
  (emmet2-preview-clear)
  (unwind-protect
      (dolist (case '((web-mode "div.card│" nil html-mode)
                      (web-mode "div.card│" "solid" js-jsx-mode)
                      (css-mode ".a{m10+p20│}" nil css-mode)
                      (tsx-ts-mode "const A=(<main>div.card│</main>);" nil js-jsx-mode)
                      (tsx-ts-mode "const A=(<main style={{m10│}} />);" nil js-jsx-mode)))
        (with-temp-buffer
          (insert (nth 1 case)) (search-backward "│") (delete-char 1)
          (let ((position (point)))
            (funcall (car case)) (goto-char position)
            (setq-local emmet2-markup-variant (nth 2 case))
            (emmet2-context--prepare)
            (let* ((analysis (emmet2-context-analyze))
                   (text (plist-get (emmet2--expand-analysis analysis) :text))
                   (abbr (plist-get analysis :abbr))
                   (expand (symbol-function 'emmet2--expand-analysis)) (calls 0)
                   (data (emmet2-capf)) (table (nth 2 data))
                   (props (nthcdr 3 data)) (doc (plist-get props :company-doc-buffer)))
              (cl-letf (((symbol-function 'emmet2--expand-analysis)
                         (lambda (value) (cl-incf calls) (funcall expand value))))
                (should (equal (all-completions abbr table) (list abbr)))
                (let ((buffer (funcall doc abbr)))
                  (should (eq buffer (funcall doc abbr)))
                  (with-current-buffer buffer
                    (should (eq major-mode (nth 3 case)))
                    (should (equal (buffer-substring-no-properties (point-min) (point-max)) text))))
                (should (= calls 1))
                (should-not (funcall doc "unrelated"))
                (funcall (plist-get props :exit-function) abbr 'finished)
                (should (= calls 1))
                (should (equal (buffer-substring-no-properties
                                (plist-get analysis :beg) (+ (plist-get analysis :beg) (length text))) text))
                (should-not (funcall doc abbr)))))))
    (emmet2-preview-clear)))

(ert-deftest emmet2-preview-real-popupinfo-documentation-path ()
  (emmet2-preview-clear)
  (unwind-protect
      (should-not
       (cadr
        (emmet2-test--completion-session
         '(basic partial-completion) nil nil nil nil nil nil nil nil nil
         (lambda ()
           (let ((text (corfu-popupinfo--get-documentation "ul>li*3")))
             (should (string-prefix-p "<ul>" text))
             (should (text-property-not-all 0 (length text) 'face nil text))
             (should (equal (buffer-string) "ul>li*3")))))))
    (emmet2-preview-clear)))

(provide 'emmet2-preview-test)
;;; emmet2-preview-test.el ends here
