;;; emmet2-capf-test.el --- Completion safety and lifecycle -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-capf-contract-test)
(require 'emmet2-preview)
(require 'typescript-ts-mode)
(require 'yasnippet)
(require 'corfu-popupinfo)

(defmacro emmet2-test--with-css-completion (input &rest body)
  "Run BODY in a displayed CSS buffer containing INPUT, using real Corfu."
  (declare (indent 1) (debug t))
  `(save-window-excursion
     (with-temp-buffer
       (set-window-buffer (selected-window) (current-buffer))
       (css-mode) (insert ".a{" ,input "}") (backward-char)
       (emmet2-mode 1) (buffer-enable-undo)
       (let ((completion-styles '(basic partial-completion))
             (completion-category-defaults nil) (completion-category-overrides nil)
             (corfu-auto-prefix 1) (corfu-auto-trigger nil)
             (corfu-on-exact-match 'show) (corfu-preview-current nil)
             (last-command-event ?a))
         (cl-letf (((symbol-function 'corfu--popup-show) #'ignore)
                   ((symbol-function 'corfu--popup-hide) #'ignore)
                   ((symbol-function 'corfu--protect) #'funcall))
           (unwind-protect (progn ,@body)
             (when completion-in-region-mode (corfu-quit))))))))

(ert-deftest emmet2-capf-confidence-and-host-gates ()
  (dolist (case '((web-mode "div│" t) (web-mode "  section│  " t) (web-mode "<p>A div│ here</p>" nil)
                  (web-mode "custom-element│" nil)
                  (web-mode "a:link│" nil) (web-mode "!│" t)
                  (web-mode "ul>li*2│" t) (web-mode "div.card│" t)
                  (web-mode "<p>This is the end.│</p>" nil) (web-mode "<p>See e.g.│</p>" nil)
                  (web-mode "ul>li.│" t)
                  (tsx-ts-mode "const A=(<p>Hello world.│</p>);" nil)
                  (web-mode "<div title='ul>li*2│'></div>" nil)
                  (web-mode "<!-- ul>li*2│ -->" nil)
                  (css-mode ".a{margin│}" t) (css-mode ".a{m│}" t)
                  (css-mode ".a{tac│}" t) (css-mode ".a{dn│}" t)
                  (scss-mode ".a{posr│}" t) (css-mode ".a{wf│}" t)
                  (css-mode ".a{all│}" t) (css-mode ".a{unknownword│}" nil)
                  (css-mode ".a{display│}" t) (css-mode ".a{ta│}" t)
                  (css-mode ".a{ins│}" t) (css-mode ".a{inset-b│}" t)
                  (css-mode ".a{color:tac│}" nil) (css-mode "tac│" nil)
                  (css-mode ".a{/* tac│ */}" nil) (css-mode ".a{content: 'tac│'}" nil)
                  (css-mode ".a{m1│}" t) (css-mode ".a{mA│}" t)
                  (css-mode ".a{c#fff│}" t) (css-mode ".a{p!│}" t)
                  (css-mode ".a{p[1px]│}" t) (css-mode ".a{p(1 + 2)│}" t)
                  (css-mode ".a{m,p│}" t) (css-mode ".a{c+bg│}" t)
                  (css-mode ".a{color: m1│}" nil) (css-mode ".card│" nil)
                  (css-mode ".a{display:fl│}" nil) (css-mode ".a{--accent:re│}" nil)
                  (css-mode ".a{future-prop:foo│}" nil) (css-mode ".a{d:n│}" nil)
                  (css-mode ".a{_:hv│}" t) (css-mode ".a{button::be│}" t)
                  (css-mode ".a{button:hv│}" t) (css-mode "button:hv│" t) (css-mode ".card:hv│" t)
                  (css-mode "#main:hv│" t) (css-mode "div.x:hv│" t) (css-mode "display:fl│" nil)
                  (css-mode "table-layout:fi│" nil) (css-mode ".a{table-layout:fi│}" nil)
                  (scss-mode "$primary:re│" nil) (scss-mode "%base:hv│" nil)
                  (scss-mode ".a{p$a│}" t) (scss-mode ".a{m$a,p$b│}" t)
                  (scss-mode ".a{p$│}" t) (scss-mode ".a{p$-│}" t)
                  (scss-mode ".a{$accent│}" nil) (scss-mode ".a{$│}" nil)
                  (web-mode "<style lang=\"scss\">.a{p$a│}</style>" t)
                  (web-mode "<style lang=\"scss\">.a{p$│}</style>" t)
                  (web-mode "<style>.a{p$│}</style>" nil) (css-mode ".a{p$│}" nil)
                  (web-mode "<style>.a{p$a│}</style>" nil) (css-mode ".a{p$a│}" nil)
                  (tsx-ts-mode "const A=(<main style={{p$│}} />);" nil)
                  (tsx-ts-mode "const A=(<main style={{p$a│}} />);" nil)
                  (css-mode ".a{button:│}" nil) (css-mode ".a{w--sidebar-width│}" t)
                  (css-mode ".a{ins32│}" t)
                  (css-mode "@│" nil) (css-mode "@md│" t)
                  (css-mode ":│" nil) (css-mode "_:hv│" t)
                  (css-mode "::b│" t) (css-mode "@media m1│" nil)
                  (fundamental-mode "ul>li*2│" nil)
                  (tsx-ts-mode "const A=(<main>ul>li*2│</main>);" t)
                  (tsx-ts-mode "const A=(<main>{items.ma│}</main>);" nil)
                  (tsx-ts-mode "const A=(<main style={{tac│}} />);" t)
                  (tsx-ts-mode "const A=(<main other={{tac│}} />);" nil)
                  (tsx-ts-mode "const A=()=>ul>li*2│;" nil)
                  (tsx-ts-mode "const A=(<main style={{m10│}} />);" t)))
    (ert-info ((format "%S" case))
      (with-temp-buffer
        (insert (nth 1 case))
        (search-backward "│") (delete-char 1)
        (let ((position (point)))
          (funcall (car case)) (goto-char position)
          (emmet2-context-js-prepare)
          (should (eq (not (null (emmet2-capf))) (nth 2 case))))))))

(ert-deftest emmet2-capf-lazy-results-and-expansion-display ()
  (emmet2-test--with-capf "p{界😀abcdefghijklmnop}*5"
    (let* ((expand (symbol-function 'emmet2-expand-analysis)) (calls 0)
           (data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (abbr (buffer-string)))
      (cl-letf (((symbol-function 'emmet2-expand-analysis)
                 (lambda (analysis) (cl-incf calls) (funcall expand analysis))))
        (should (eq (completion-metadata-get (completion-metadata abbr table nil) 'category) 'emmet2))
        (should (= calls 0))
        (should (equal (all-completions abbr table) (list abbr)))
        (should (test-completion abbr table))
        (should (equal (try-completion abbr table) abbr))
        (let ((row (car (funcall (plist-get props :affixation-function)
                                 (all-completions abbr table)))))
          (should (equal (get-text-property 0 'display (car row)) ""))
          (should (equal (cadr row)
                         (string-join (make-list 5 "<p>界😀abcdefghijklmnop</p>") " ")))
          (should (equal (get-text-property 0 'emmet2--label (car row)) (cadr row)))
          (should (equal (caddr row) "")))
        (should-not (plist-member props :annotation-function))
        ;; Plain-text rows: no kind, so icon margin formatters stay inactive.
        (should-not (plist-member props :company-kind))
        (should-not (plist-member props :company-prefix-length))
        (should (= calls 1))
        (should (equal (buffer-string) abbr))))))

(ert-deftest emmet2-capf-multiline-only-formatted-preview ()
  (unwind-protect
      (dolist (abbr '("m10+p20" "tac"))
        (with-temp-buffer
          (css-mode) (insert ".a{" abbr "}") (backward-char)
          (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
                 (source (buffer-string))
                 (text (if (equal abbr "tac") "text-align: center;"
                         "margin: 10px;\n   padding: 20px;"))
                 (row (car (funcall (plist-get props :affixation-function)
                                    (all-completions abbr (nth 2 data))))))
            (should (equal (car (all-completions abbr (nth 2 data))) abbr))
            ;; The row shows the last property; the preview keeps the rest.
            (should (equal (cadr row) (if (equal abbr "tac") text "padding: 20px;")))
            (if (equal abbr "tac")
                (should-not (funcall (plist-get props :company-doc-buffer) abbr))
              (with-current-buffer (funcall (plist-get props :company-doc-buffer) abbr)
                (should (equal (buffer-substring-no-properties (point-min) (point-max))
                               "margin: 10px;\npadding: 20px;"))
                (should (text-property-not-all (point-min) (point-max) 'face nil))))
            (should (equal (buffer-string) source))
            (funcall (plist-get props :exit-function) abbr 'finished)
            (should (equal (buffer-string) (concat ".a{" text "}"))))))
    (emmet2-preview-clear)))

(ert-deftest emmet2-capf-display-highlights-literal-matches-without-changing-results ()
  (dolist (case '(("tac" "text-align: center;" (0 5 12))
                  ("m10," "margin: 10px;" (0 8 9))
                  ("TAC" "text-align: center;" (0 5 12))
                  ("wf" "width: 100%;" nil)))
    (pcase-let* ((`(,input ,text ,positions) case)
                 (result (emmet2-result-create text))
                 (label (emmet2-capf--display (plist-get result :text) input)))
      (should (equal label text))
      (should (equal (cl-loop for i below (length label)
                              when (get-text-property i 'face label) collect i)
                     positions))
      (should-not (text-property-not-all 0 (length text) 'face nil (plist-get result :text))))))

(ert-deftest emmet2-capf-css-prefix-choices-and-distinct-acceptance ()
  (with-temp-buffer
    (css-mode) (insert ".a{ta}") (backward-char)
    (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (candidates (all-completions "ta" table))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (labels (mapcar #'cadr rows)))
      (dolist (text '("text-align: ;" "text-align: left;" "text-align: center;"
                      "text-align: right;" "text-align: justify;" "touch-action: ;"))
        (should (member text labels)))
      (should (equal (car labels) "text-align: ;"))
      (should (<= (length labels) emmet2-capf--limit))
      (should (= (length labels) (length (delete-dups (copy-sequence labels)))))
      (should (cl-every (lambda (candidate) (equal candidate "ta")) candidates))
      (let ((selected (nth (cl-position "text-align: right;" labels :test #'equal) candidates)))
        (funcall (plist-get props :exit-function) selected 'finished)
        (should (equal (buffer-string) ".a{text-align: right;}"))))))

(ert-deftest emmet2-capf-pseudo-menu-is-independent-of-insertion ()
  (dolist (case '((":be" "::before" "::before")
                  ("_:be" "::before" "::before")
                  ("&:be" "::before" "&::before")
                  ("button:be" "::before" "button::before")
                  (".card:be" "::before" ".card::before")
                  ("&:hv:be" ":hover::before" "&:hover::before")
                  ("&::part" "::part()" "&::part()")
                  ("&:not" ":not()" "&:not()")))
    (emmet2-test--with-css-completion (car case)
      (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions (car case) (nth 2 data))))
             (entry (get-text-property 0 'emmet2--choice candidate))
             (result (copy-tree (plist-get entry :result)))
             (row (car (funcall (plist-get props :affixation-function) (list candidate)))))
        (should (equal (cadr row) (cadr case)))
        (should (equal (nth 2 case) (plist-get result :text)))
        (should (text-property-not-all 0 (length (cadr row)) 'face nil (cadr row)))
        (should-not (funcall (plist-get props :company-doc-buffer) candidate))
        (should (equal (plist-get entry :result) result))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (equal (buffer-string) (concat ".a{" (plist-get result :text) "}")))
        (should (= (point) (+ 4 (plist-get result :cursor))))))))

(ert-deftest emmet2-capf-pseudo-preview-and-cursor ()
  (dolist (mode '(css-mode scss-mode))
    (dolist (command '(corfu-auto--complete-deferred emmet2-complete))
      (dolist (case '(("&:fu" ":focus" "&:focus│")
                      (":be" "::before" "::before│")
                      (":af" "::after" "::after│")
                      ("&::be" "::before" "&::before│")
                      ("&::part" "::part()" "&::part(│)" "button")
                      ("&:not" ":not()" "&:not(│)" ".disabled")))
        (ert-info ((format "%S %S %S" mode command case))
          (emmet2-test--with-css-completion (car case)
            (unless (eq mode major-mode) (funcall mode) (emmet2-mode 1))
            (setq-local css-indent-offset 2)
            (let ((completion-in-region-function #'corfu--in-region-1))
              (funcall command)
              (when (eq command 'emmet2-complete) (corfu--exhibit)))
            (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) (nth 1 case)))
            (should-not (corfu-popupinfo--get-documentation (car corfu--candidates)))
            (corfu-insert)
            (should (equal (concat (buffer-substring (point-min) (point)) "│"
                                   (buffer-substring (point) (point-max)))
                           (concat ".a{" (nth 2 case) "}")))
            (should-not mark-active)
            ;; Typed arguments land inside the parentheses.
            (when (nth 3 case)
              (insert (nth 3 case))
              (should (looking-at ")}"))))))))
  (emmet2-preview-clear))

(ert-deftest emmet2-capf-pseudo-tail-edit-retains-only-current-choices ()
  (emmet2-test--with-css-completion "&::b"
    (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (old (car (all-completions "&::b" table))))
      (should (equal (plist-get (get-text-property 0 'emmet2--choice old) :text) "&::before"))
      (insert "e")
      (save-excursion (insert " {}"))
      ;; The result stays the same, but the old source revision cannot insert.
      (funcall (plist-get props :exit-function) old 'finished)
      (should (equal (buffer-string) ".a{&::be {}}"))
      (let ((candidate (car (all-completions "&::be" table))))
        (should (equal (plist-get (get-text-property 0 'emmet2--choice candidate) :text) "&::before"))
        (funcall (plist-get props :exit-function) old 'finished)
        (should (equal (buffer-string) ".a{&::be {}}"))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (equal (buffer-string) ".a{&::before {}}"))))))

(ert-deftest emmet2-capf-complex-selector-preview-typing-and-acceptance ()
  (emmet2-test--with-css-completion ".a,[data-label='a:b'] > .child:hover.active::b"
    (setq-local css-indent-offset 2)
    (corfu-auto--complete-deferred)
    (let ((table (nth 2 completion-in-region--data)))
      (insert "e")
      (let ((this-command 'self-insert-command)) (corfu--post-command))
      (should (eq table (nth 2 completion-in-region--data)))
      (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) "::before"))
      (should-not (corfu-popupinfo--get-documentation (car corfu--candidates)))
      (corfu-insert)
      (should (equal (buffer-string)
                     ".a{.a,[data-label='a:b'] > .child:hover.active::before}"))
      (should (looking-back "::before" (line-beginning-position)))
      (should (looking-at "}")))))

(ert-deftest emmet2-capf-background-choices-stay-properties ()
  (emmet2-test--with-css-completion "bg"
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "bg" (nth 2 data)))
           (labels (mapcar #'cadr (funcall (plist-get props :affixation-function) candidates)))
           (index (cl-position "background: none;" labels :test #'equal)))
      (should (numberp index))
      (should-not (cl-some (lambda (label) (string-match-p "{" label)) labels))
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) ".a{background: none;}")))))

(ert-deftest emmet2-capf-fuzzy-search-includes-canonical-properties ()
  (emmet2-test--with-css-completion "ins"
    (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (candidates (all-completions "ins" table))
           (labels (mapcar #'cadr (funcall (plist-get props :affixation-function) candidates)))
           (index (cl-position "inset-block: ;" labels :test #'equal)))
      (should (equal (car labels) "inset: ;"))
      (should-not (member "ins: ;" labels))
      (should (numberp index))
      (should (equal (cl-loop for i below (length (car labels))
                              when (get-text-property i 'face (car labels)) collect i) '(0 1 2)))
      (should (equal labels (mapcar #'cadr (funcall (plist-get props :affixation-function)
                                                   (all-completions "ins" table)))))
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) ".a{inset-block: ;}"))))
  (emmet2-test--with-css-completion "size"
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (rows (funcall (plist-get props :affixation-function) (all-completions "size" (nth 2 data)))))
      (should (member "inline-size: ;" (mapcar #'cadr rows))))))

(ert-deftest emmet2-capf-fuzzy-properties-continue-through-hyphens ()
  (emmet2-test--with-css-completion "ins"
    (corfu-auto--complete-deferred)
    (let ((table (nth 2 completion-in-region--data)))
      (insert "et-b")
      (let ((this-command 'self-insert-command)) (corfu--post-command))
      (should completion-in-region-mode)
      (should (eq table (nth 2 completion-in-region--data)))
      (corfu-insert)
      (should (equal (buffer-string) ".a{inset-block: ;}"))
      (undo-only 1)
      (should (equal (buffer-string) ".a{inset-b}")))))

(ert-deftest emmet2-capf-canonical-property-values-preview-acceptance-and-undo ()
  (unwind-protect
      (dolist (pair '(("inset-block-10" . "inset-block: -10px;")
                       ("inset-block[10px]" . "inset-block: 10px;")
                       ("inset-block--space" . "inset-block: var(--space);")))
        (emmet2-test--with-css-completion (concat "ovh," (car pair))
          (corfu-auto--complete-deferred)
          (should completion-in-region-mode)
          (should (equal (corfu-popupinfo--get-documentation (car corfu--candidates))
                         (concat "overflow: hidden;\n" (cdr pair))))
          (corfu-insert)
          (should (equal (buffer-string) (concat ".a{overflow: hidden;\n   " (cdr pair) "}")))
          (undo-only 1)
          (should (equal (buffer-string) (concat ".a{ovh," (car pair) "}")))))
    (emmet2-preview-clear)))

(ert-deftest emmet2-capf-corfu-alternative-cursor-and-one-undo ()
  (dolist (text '("text-align: right;" "touch-action: ;"))
    (emmet2-test--with-css-completion "ta"
      (corfu-auto--complete-deferred)
      (should completion-in-region-mode)
      (let* ((candidates corfu--candidates)
             (rows (cdr (corfu--affixate candidates)))
             (index (cl-position text (mapcar #'cadr rows) :test #'equal))
             (this-command 'corfu-insert) (last-command nil))
        (should (> index 0))
        (should (cl-every (lambda (row) (equal (get-text-property 0 'display (car row)) "")) rows))
        (corfu--goto index)
        (corfu-insert)
        (should (equal (buffer-string) (concat ".a{" text "}")))
        (when (equal text "touch-action: ;")
          (should (eq (char-after) ?\;)))
        (should-not mark-active)
        (undo-only 1)
        (should (equal (buffer-string) ".a{ta}"))))))

(ert-deftest emmet2-capf-corfu-accepts-latest-revision ()
  (emmet2-test--with-css-completion "m10"
    (corfu-auto--complete-deferred)
    (insert "0")
    (let ((this-command 'self-insert-command)) (corfu--post-command))
    (should completion-in-region-mode)
    (corfu-insert)
    (should (equal (buffer-string) ".a{margin: 100px;}"))
    (undo-only 1)
    (should (equal (buffer-string) ".a{m100}"))))

(ert-deftest emmet2-capf-corfu-separator-retains-choices-and-continues-properties ()
  (dolist (separator '("," "+"))
    (dolist (input '("m10" "ta" "m10,p20" "m10+p20" "ct['a,b+c']"))
      (emmet2-test--with-css-completion input
        (corfu-auto--complete-deferred)
        (let ((table (nth 2 completion-in-region--data))
              (labels (mapcar #'cadr (cdr (corfu--affixate corfu--candidates)))))
          (cl-letf (((symbol-function 'corfu--popup-hide)
                     (lambda () (ert-fail "A pending separator must keep the popup visible"))))
            (insert separator)
            (let ((this-command 'self-insert-command)) (corfu--post-command))
            (should completion-in-region-mode)
            (should (eq table (nth 2 completion-in-region--data)))
            (should (equal (mapcar #'cadr (cdr (corfu--affixate corfu--candidates))) labels))
            (insert "ta")
            (let ((this-command 'self-insert-command)) (corfu--post-command))
            (should (> corfu--total 1))
            (should (cl-some (lambda (row) (string-suffix-p "text-align: center;" (cadr row)))
                             (cdr (corfu--affixate corfu--candidates))))))))))

(ert-deftest emmet2-capf-corfu-pending-separator-acceptance-and-undo ()
  (dolist (separator '("," "+"))
    (emmet2-test--with-css-completion "m10"
      (corfu-auto--complete-deferred)
      (let* ((props (nth 4 completion-in-region--data))
             (exit (plist-get props :exit-function))
             (old (car corfu--candidates)))
        (insert separator)
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (funcall exit old 'finished)
        (should (equal (buffer-string) (concat ".a{m10" separator "}")))
        (should completion-in-region-mode)
        (corfu-insert)
        (should (equal (buffer-string) ".a{margin: 10px;}"))
        (undo-only 1)
        (should (equal (buffer-string) (concat ".a{m10" separator "}")))))))

(ert-deftest emmet2-capf-corfu-sass-variable-prefix-keeps-the-session ()
  (dolist (input '("p" "padding" "inset-b"))
    (emmet2-test--with-css-completion input
      (scss-mode) (emmet2-mode 1)
      (corfu-auto--complete-deferred)
      (let* ((table (nth 2 completion-in-region--data))
             (anchor (nth 0 completion-in-region--data))
             (exit (plist-get (nth 4 completion-in-region--data) :exit-function))
             (old (car corfu--candidates))
             (property (if (equal input "inset-b") "inset-block" "padding")))
        (cl-letf (((symbol-function 'corfu--popup-hide)
                   (lambda () (ert-fail "A Sass variable prefix must keep the popup visible"))))
          (dolist (part '("$" "-" "gutter"))
            (insert part)
            (let ((this-command 'self-insert-command)) (corfu--post-command))
            (should completion-in-region-mode)
            (should (eq table (nth 2 completion-in-region--data)))
            (should (equal anchor (nth 0 completion-in-region--data)))
            (should (string-prefix-p (concat property ": $")
                                     (cadar (cdr (corfu--affixate corfu--candidates)))))))
        (funcall exit old 'finished)
        (should (equal (buffer-string) (concat ".a{" input "$-gutter}")))
        (corfu-insert)
        (should (equal (buffer-string) (concat ".a{" property ": $-gutter;}")))
        (undo-only 1)
        (should (equal (buffer-string) (concat ".a{" input "$-gutter}")))))))

(ert-deftest emmet2-capf-sass-pending-variable-acceptance-preserves-dollar ()
  (emmet2-test--with-css-completion "p"
    (scss-mode) (emmet2-mode 1)
    (corfu-auto--complete-deferred)
    (insert "$")
    (let ((this-command 'self-insert-command)) (corfu--post-command))
    (should completion-in-region-mode)
    (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) "padding: $;"))
    (corfu-insert)
    (should (equal (buffer-string) ".a{padding: $;}"))
    (undo-only 1)
    (should (equal (buffer-string) ".a{p$}"))))

(ert-deftest emmet2-capf-corfu-rows-show-only-the-last-property ()
  (emmet2-test--with-css-completion "ovh"
    (corfu-auto--complete-deferred)
    (let ((table (nth 2 completion-in-region--data)))
      (dolist (step '(("," "overflow: hidden;" nil)
                      ("ta" "text-align: ;" "overflow: hidden;\ntext-align: ;")
                      ("," "text-align: ;" "overflow: hidden;\ntext-align: ;")
                      ("m10+p20" "padding: 20px;"
                       "overflow: hidden;\ntext-align: ;\nmargin: 10px;\npadding: 20px;")))
        (insert (car step))
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should completion-in-region-mode)
        (should (eq table (nth 2 completion-in-region--data)))
        (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) (cadr step)))
        (should (equal (corfu-popupinfo--get-documentation (car corfu--candidates))
                       (nth 2 step)))))))

(ert-deftest emmet2-capf-current-fragment-keeps-complete-insertion-and-undo ()
  (emmet2-test--with-css-completion "c,ta"
    (corfu-auto--complete-deferred)
    (let* ((rows (cdr (corfu--affixate corfu--candidates)))
           (index (cl-position "text-align: center;" (mapcar #'cadr rows) :test #'equal)))
      (should (numberp index))
      (should (equal (corfu-popupinfo--get-documentation (nth index corfu--candidates))
                     "color: ;\ntext-align: center;"))
      (corfu--goto index)
      (corfu-insert)
      (should (equal (buffer-string) ".a{color: ;\n   text-align: center;}"))
      (should (eq (char-after) ?\;))
      (undo-only 1)
      (should (equal (buffer-string) ".a{c,ta}")))))

(ert-deftest emmet2-capf-current-fragment-preview-includes-confirmed-properties ()
  (dolist (case '(("ovh,ta" "text-align: ;" "overflow: hidden;\ntext-align: ;")
                  ("ovh,ta," "text-align: ;" "overflow: hidden;\ntext-align: ;")
                  ("ovh+ta+" "text-align: ;" "overflow: hidden;\ntext-align: ;")
                  ("ovh,posa" "position: absolute; z-index: ;"
                   "overflow: hidden;\nposition: absolute;\nz-index: ;")))
    (emmet2-test--with-css-completion (car case)
      (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions (car case) (nth 2 data))))
             (label (cadar (funcall (plist-get props :affixation-function) (list candidate)))))
        (should (equal label (nth 1 case)))
        (should (get-text-property 0 'face label))
        (with-current-buffer (funcall (plist-get props :company-doc-buffer) candidate)
          (should (equal (buffer-substring-no-properties (point-min) (point-max)) (nth 2 case))))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (equal (buffer-string)
                       (concat ".a{" (string-replace "\n" "\n   " (nth 2 case)) "}")))))))

(ert-deftest emmet2-capf-current-fragment-honors-nested-and-quoted-commas ()
  (dolist (input '("p[calc(1px,2px)],ta" "ct['a,b'],ta"))
    (emmet2-test--with-css-completion input
      (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions input (nth 2 data)))))
        (should (equal (cadar (funcall (plist-get props :affixation-function) (list candidate)))
                       "text-align: ;"))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (string-match-p (if (string-prefix-p "p" input) "calc(1px,2px)" "'a,b'")
                                (buffer-string)))))))

(ert-deftest emmet2-capf-keeps-complete-obsolete-properties ()
  (dolist (input '("clip" "clip1" "clip[none]"))
    (emmet2-test--with-css-completion input
      (let* ((expected (plist-get (emmet2-expand-analysis (emmet2-context-analyze t)) :text))
             (data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions input (nth 2 data)))))
        (should (equal (cadar (funcall (plist-get props :affixation-function) (list candidate)))
                       expected))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (equal (buffer-string) (concat ".a{" expected "}")))))))

(ert-deftest emmet2-capf-current-fragment-is-prepared-once-per-revision ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let ((expand (symbol-function 'emmet2-css--program))
          (prefix (symbol-function 'emmet2-engine-stylesheet-render))
          (prepare (symbol-function 'emmet2-capf--preview-text))
          (display (symbol-function 'emmet2-capf--display))
          expanded (prefix-calls 0) (prepared 0) (displayed 0))
      (cl-letf (((symbol-function 'emmet2-css--program)
                 (lambda (abbreviation at-rule)
                   (push abbreviation expanded) (funcall expand abbreviation at-rule)))
                ((symbol-function 'emmet2-engine-stylesheet-render)
                 (lambda (declaration &rest options)
                   ;; The confirmed prefix is resolved and rendered once.
                   (when (equal (emmet2-stylesheet--node-name declaration) "overflow")
                     (cl-incf prefix-calls))
                   (apply prefix declaration options)))
                ((symbol-function 'emmet2-capf--preview-text)
                 (lambda (&rest args) (cl-incf prepared) (apply prepare args)))
                ((symbol-function 'emmet2-capf--display)
                 (lambda (&rest args) (cl-incf displayed) (apply display args))))
        (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
               (candidates (all-completions "ovh,ta" table))
               (calls (length expanded)))
          (should (= (cl-count "ovh" expanded :test #'equal) 1))
          (should (= prefix-calls 1))
          (should (= prepared (length candidates)))
          (should (= displayed (length candidates)))
          (dotimes (_ 3)
            (funcall (plist-get props :affixation-function) candidates)
            (dolist (candidate candidates) (funcall (plist-get props :company-doc-buffer) candidate)))
          (should (= calls (length expanded)))
          (should (= prepared (length candidates)))
          (should (= displayed (length candidates)))
          (insert "c")
          (let ((next (all-completions "ovh,tac" table)))
            (should (equal (cadar (funcall (plist-get props :affixation-function) next))
                           "text-align: center;"))
            (should (= (cl-count "ovh" expanded :test #'equal) 1))
            (should (= prefix-calls 1))
            (should (= prepared (+ (length next) (length candidates))))
            (should (= displayed (+ (length next) (length candidates))))))))))

(ert-deftest emmet2-capf-plus-prefix-is-resolved-once-per-revision ()
  (emmet2-test--with-css-completion "m10+p5+bd1#2s+dib+b"
    (let ((search (symbol-function 'emmet2-css-search)) (calls 0))
      (cl-letf (((symbol-function 'emmet2-css-search)
                 (lambda (&rest args) (cl-incf calls) (apply search args))))
        (let* ((data (emmet2-capf)) (table (nth 2 data))
               (candidates (all-completions "m10+p5+bd1#2s+dib+b" table)))
          (should (> (length candidates) 1))
          ;; Four earlier properties and one choice list, not one per choice.
          (should (<= calls 8))
          (should (string-prefix-p "margin: 10px;" (plist-get (get-text-property 0 'emmet2--choice (car candidates))
                                                              :text))))))))

(ert-deftest emmet2-capf-classifies-each-context-revision-once ()
  ;; Each change is an input of the analysis, so it classifies the host again.
  (dolist (change (list nil (lambda (data) (goto-char (nth 1 data)))
                        (lambda (_) (narrow-to-region (point-min) (1- (point-max))))
                        (lambda (_) (setq-local web-mode-engine "php"))
                        (lambda (_) (setq-local web-mode-content-type "css"))))
    (with-temp-buffer
      (insert "<style>.a{m10}</style>") (web-mode) (emmet2-mode 1) (search-backward "10}</style>")
      (let ((analyze (symbol-function 'emmet2-context-analyze)) (calls 0))
        (cl-letf (((symbol-function 'emmet2-context-analyze)
                   (lambda (&rest args) (cl-incf calls) (apply analyze args))))
          (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
                 (candidates (all-completions "m10" table)))
            ;; Frontend queries of one revision reuse the table's classification.
            (dotimes (_ 3) (all-completions "m10" table) (test-completion "m10" table))
            (funcall (plist-get props :affixation-function) candidates)
            (funcall (plist-get props :company-doc-buffer) (car candidates))
            (should (= calls 1))
            (when change
              (funcall change data)
              (all-completions "m10" table)
              (should (> calls 1)))))))))

(ert-deftest emmet2-capf-last-property-choices-equal-whole-expansions ()
  ;; A choice expands the confirmed prefix once and only its last property.
  (dolist (input '("m10+p5+bd1#2s+posa+dib+fz16" "allA+t-a" "ct['a,b']+c!" "w--x+ins32" "ovh,m10+p5"))
    (dolist (tsx '(nil t))
      (ert-info ((format "%s %s" input tsx))
        (with-temp-buffer
          (if (not tsx)
              (progn (insert ".a{" input "}") (css-mode) (backward-char))
            (insert "const A=(<main style={{" input "}} />);") (tsx-ts-mode) (search-backward "}}"))
          (emmet2-mode 1)
          (let ((analysis (emmet2-context-analyze)))
            (should (equal (plist-get (car (plist-get (emmet2-capf--choices analysis) :choices)) :result)
                           (emmet2-expand-analysis analysis)))))))))

(ert-deftest emmet2-capf-confirmed-prefix-is-replaced-after-edits-and-cleared-without-a-comma ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let ((expand (symbol-function 'emmet2-css--program)) expanded)
      (cl-letf (((symbol-function 'emmet2-css--program)
                 (lambda (abbreviation at-rule)
                   (push abbreviation expanded) (funcall expand abbreviation at-rule))))
        (let* ((data (emmet2-capf)) (table (nth 2 data))
               (props (nthcdr 3 data)))
          (all-completions "ovh,ta" table)
          (dolist (step '(("ova,ta" "overflow: auto;\ntext-align: ;")
                          ("ovh,tac" "overflow: hidden;\ntext-align: center;")
                          ("tac" nil)
                          ("ovh,tac" "overflow: hidden;\ntext-align: center;")))
            (delete-region (car data) (point)) (insert (car step))
            (let* ((candidate (car (all-completions (car step) table)))
                   (preview (funcall (plist-get props :company-doc-buffer) candidate)))
              (should candidate)
              (if (cadr step)
                  (with-current-buffer preview
                    (should (equal (buffer-string) (cadr step))))
                (should-not preview))))
          (should (= (cl-count "ovh" expanded :test #'equal) 3))
          (should (= (cl-count "ova" expanded :test #'equal) 1))
          (funcall (plist-get props :exit-function)
                   (car (all-completions "ovh,tac" table)) 'finished)
          (should (equal (buffer-string) ".a{overflow: hidden;\n   text-align: center;}")))))))

(ert-deftest emmet2-capf-confirmed-prefix-cannot-outlive-render-settings ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let* ((data (emmet2-capf)) (table (nth 2 data))
           (exit (plist-get (nthcdr 3 data) :exit-function))
           (candidate (car (all-completions "ovh,ta" table))))
      (setq-local css-indent-offset (1+ css-indent-offset))
      (insert "c")
      (should-not (all-completions "ovh,tac" table))
      (funcall exit candidate 'finished)
      (should (equal (buffer-string) ".a{ovh,tac}")))))

(ert-deftest emmet2-capf-scale-functions-reach-scss-completion ()
  (with-temp-buffer
    (scss-mode) (insert ".a{p(1)(2)}") (backward-char)
    (should-not (all-completions "p(1)(2)" (nth 2 (emmet2-capf))))
    (let* ((emmet2-css-scale-functions '((t . "rhythm")))
           (table (nth 2 (emmet2-capf)))
           (choice (car (all-completions "p(1)(2)" table))))
      (should (equal (plist-get (plist-get (get-text-property 0 'emmet2--choice choice) :result) :text)
                     "padding: rhythm(1) rhythm(2);"))
      ;; A changed option ends the table's session.
      (setq emmet2-css-scale-functions '((t . "space")))
      (should-not (all-completions "p(1)(2)" table)))))

(ert-deftest emmet2-capf-bare-words-search-once-and-decline-without-choices ()
  (let ((calls 0))
    (cl-letf* ((search (symbol-function 'emmet2-css-search))
               ((symbol-function 'emmet2-css-search)
                (lambda (&rest args) (cl-incf calls) (apply search args))))
      (with-temp-buffer
        (css-mode) (insert ".a{colo}") (backward-char)
        (should (all-completions "colo" (nth 2 (emmet2-capf))))
        (should (= calls 1))
        ;; A declined word costs one search too.
        (erase-buffer) (insert ".a{zzqq}") (backward-char)
        (setq calls 0)
        (should-not (emmet2-capf))
        (should (= calls 1))))))

(ert-deftest emmet2-capf-reuses-results-with-fresh-highlights-and-choice-identities ()
  (emmet2-test--with-css-completion "in"
    (let ((expand (symbol-function 'emmet2-css--declarations)) expanded)
      (cl-letf (((symbol-function 'emmet2-css--declarations)
                 (lambda (property at-rule scale)
                   (push (emmet2-css--choice-token property) expanded)
                   (funcall expand property at-rule scale))))
        (let* ((data (emmet2-capf)) (table (nth 2 data))
               (exit (plist-get (nthcdr 3 data) :exit-function))
               (old (cl-find-if (lambda (candidate)
                                  (equal (plist-get (get-text-property 0 'emmet2--choice candidate) :abbreviation) "inset"))
                                (all-completions "in" table)))
               (entry (get-text-property 0 'emmet2--choice old)))
          (should (= 1 (cl-count "inset" expanded :test #'equal)))
          (should-not (get-text-property 2 'face (plist-get entry :display)))
          (insert "s")
          (let* ((next (cl-find-if (lambda (candidate)
                                    (equal (plist-get (get-text-property 0 'emmet2--choice candidate) :abbreviation) "inset"))
                                  (all-completions "ins" table)))
                 (fresh (get-text-property 0 'emmet2--choice next)))
            (should (eq (plist-get entry :result) (plist-get fresh :result)))
            (should-not (eq entry fresh))
            (should (get-text-property 2 'face (plist-get fresh :display)))
            (should-not (get-text-property 2 'face (plist-get entry :display)))
            (should (= 1 (cl-count "inset" expanded :test #'equal))))
          ;; Returning to identical input must not make an old candidate current.
          (delete-char -1)
          (let ((current (all-completions "in" table)))
            (should current)
            (funcall exit old 'finished)
            (should (equal (buffer-string) ".a{in}"))))))))

(ert-deftest emmet2-capf-retains-only-the-preceding-candidate-set ()
  (emmet2-test--with-css-completion "in"
    (let ((expand (symbol-function 'emmet2-css--declarations)) expanded)
      (cl-letf (((symbol-function 'emmet2-css--declarations)
                 (lambda (property at-rule scale)
                   (push (emmet2-css--choice-token property) expanded)
                   (funcall expand property at-rule scale))))
        (let ((table (nth 2 (emmet2-capf))))
          (all-completions "in" table)
          (should (= 1 (cl-count "inline-size" expanded :test #'equal)))
          (insert "set")
          (all-completions "inset" table)
          (delete-char -3)
          (all-completions "in" table)
          (should (= 2 (cl-count "inline-size" expanded :test #'equal))))))))

(ert-deftest emmet2-capf-affixation-validates-the-whole-batch ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ovh,ta" (nth 2 data)))
           (affix (plist-get props :affixation-function))
           (analyze (symbol-function 'emmet2-context-analyze)) (analyses 0))
      (should (> (length candidates) 1))
      (cl-letf (((symbol-function 'emmet2-context-analyze)
                 (lambda (&rest args) (cl-incf analyses) (apply analyze args))))
        ;; An unchanged context revision needs no analysis; a changed one needs
        ;; one for the whole batch, not one per row.
        (funcall affix candidates)
        (should (= analyses 0))
        (narrow-to-region (point-min) (1- (point-max)))
        (let ((rows (funcall affix candidates)))
          (should (= analyses 1))
          (should (equal (mapcar #'cadr rows)
                         (mapcar (lambda (candidate)
                                   (plist-get (get-text-property 0 'emmet2--choice candidate) :display))
                                 candidates)))
          (should (equal (mapcar #'car rows) candidates)))
        (widen))
      ;; Matching text from another table cannot borrow this table's result.
      (let ((foreign (car (all-completions "ovh,ta" (nth 2 (emmet2-capf))))))
        (should (equal (cadar (funcall affix (list foreign))) "")))
      ;; Display callbacks may not refresh an input revision after an edit.
      (insert "c")
      (should (cl-every (lambda (row) (equal (cadr row) "")) (funcall affix candidates)))
      (dolist (candidate candidates)
        (should-not (funcall (plist-get props :company-doc-buffer) candidate))
        (funcall (plist-get props :exit-function) candidate 'finished))
      (should (equal (buffer-string) ".a{ovh,tac}")))))

(ert-deftest emmet2-capf-current-fragment-preserves-css-in-js-insertion ()
  (with-temp-buffer
    (insert "const A=(<main style={{ovh,ta}} />);") (tsx-ts-mode)
    (goto-char (point-min)) (search-forward "ovh,ta")
    (emmet2-context-js-prepare)
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ovh,ta" (nth 2 data)))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (index (cl-position "textAlign: \"right\"" (mapcar #'cadr rows) :test #'equal)))
      (should (numberp index))
      (should-not (funcall (plist-get props :company-doc-buffer) (nth index candidates)))
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) "const A=(<main style={{overflow: \"hidden\", textAlign: \"right\"}} />);")))))

(ert-deftest emmet2-capf-corfu-css-in-js-plus-retains-choices ()
  (emmet2-test--with-css-completion "ovh"
    (erase-buffer)
    (insert "const A=(<main style={{ovh}} />);") (tsx-ts-mode)
    (goto-char (point-min)) (search-forward "ovh")
    (emmet2-mode 1) (setq buffer-undo-list nil)
    (emmet2-context-js-prepare)
    (corfu-auto--complete-deferred)
    (let ((table (nth 2 completion-in-region--data))
          (labels (mapcar #'cadr (cdr (corfu--affixate corfu--candidates)))))
      (should completion-in-region-mode)
      (cl-letf (((symbol-function 'corfu--popup-hide)
                 (lambda () (ert-fail "A CSS-in-JS property plus must keep the popup visible"))))
        (insert "+")
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should completion-in-region-mode)
        (should (eq table (nth 2 completion-in-region--data)))
        (should (equal (mapcar #'cadr (cdr (corfu--affixate corfu--candidates))) labels))
        (insert "tac")
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should (eq table (nth 2 completion-in-region--data)))
        (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) "textAlign: \"center\"")))
      (corfu-insert)
      (should (equal (buffer-string)
                     "const A=(<main style={{overflow: \"hidden\", textAlign: \"center\"}} />);"))
      (undo-only 1)
      (should (equal (buffer-string) "const A=(<main style={{ovh+tac}} />);")))))

(ert-deftest emmet2-capf-pending-separator-keeps-strict-syntax-boundaries ()
  (dolist (input '("m10,," "m10,+" "m10++" "m10+," "m10,,p5+" "m10++p5+"
                  "p[1," "p(calc(1px," "p[1+" "w[calc(1px+" ".a+" "button:hv+" ":hv+" "@md+"))
    (with-temp-buffer
      (css-mode) (insert ".a{" input "}") (backward-char)
      (when-let* ((data (emmet2-capf)))
        (should-not (all-completions input (nth 2 data))))))
  (with-temp-buffer
    (css-mode) (insert ".a{p[calc(1px,2px)],}") (backward-char)
    (let* ((data (emmet2-capf))
           (candidate (car (all-completions "p[calc(1px,2px)]," (nth 2 data)))))
      (funcall (plist-get (nthcdr 3 data) :exit-function) candidate 'finished)
      (should (equal (buffer-string) ".a{padding: calc(1px,2px);}")))))

(ert-deftest emmet2-capf-corfu-choices-through-styles-manual-and-tab ()
  (dolist (styles '((basic partial-completion) (partial-completion basic) (partial-completion)))
    (dolist (automatic '(nil t))
      (emmet2-test--with-css-completion "ta"
        (let ((completion-styles styles)
              (completion-in-region-function #'corfu--in-region-1)
              (completion-cycle-threshold nil))
          (if automatic (corfu-auto--complete-deferred)
            (emmet2-complete) (corfu--exhibit))
          (should (> corfu--total 1))
          (let* ((rows (cdr (corfu--affixate corfu--candidates)))
                 (index (cl-position "text-align: center;" (mapcar #'cadr rows) :test #'equal)))
            (should (> index 0))
            (corfu--goto index)
            (corfu-complete)
            (should (equal (buffer-string) ".a{text-align: center;}"))))))))

(ert-deftest emmet2-capf-corfu-middle-edit-keeps-session ()
  (emmet2-test--with-css-completion "m10"
    (backward-char)
    (corfu-auto--complete-deferred)
    (insert "2")
    (cl-letf (((symbol-function 'corfu--popup-hide)
               (lambda () (ert-fail "Editing inside the abbreviation must not hide the popup"))))
      (let ((this-command 'self-insert-command)) (corfu--post-command)))
    (should completion-in-region-mode)
    (corfu-insert)
    (should (equal (buffer-string) ".a{margin: 120px;}"))))

(ert-deftest emmet2-capf-old-choice-cannot-be-accepted-after-input-roundtrip ()
  (emmet2-test--with-css-completion "m10"
    (let* ((data (emmet2-capf)) (table (nth 2 data))
           (exit (plist-get (nthcdr 3 data) :exit-function))
           (old (car (all-completions "m10" table))))
      (insert "0") (should (all-completions "m100" table))
      (delete-char -1)
      (let ((current (car (all-completions "m10" table))))
        (funcall exit old 'finished)
        (should (equal (buffer-string) ".a{m10}"))
        (funcall exit current 'finished)
        (should (equal (buffer-string) ".a{margin: 10px;}"))))))

(ert-deftest emmet2-capf-css-in-js-alternative-keeps-host-formatting ()
  (with-temp-buffer
    (insert "const A=(<main style={{ta}} />);") (tsx-ts-mode)
    (search-backward "ta}}") (forward-char 2) (emmet2-mode 1)
    (emmet2-context-analyze)
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ta" (nth 2 data)))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (index (cl-position "textAlign: \"right\"" (mapcar #'cadr rows) :test #'equal)))
      (should index)
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) "const A=(<main style={{textAlign: \"right\"}} />);")))))

(ert-deftest emmet2-capf-corfu-multiline-to-single-line-hides-info-only ()
  (emmet2-test--with-css-completion "m10+p20"
    (corfu-auto--complete-deferred)
    (should (string-match-p "margin: 10px;\n" (corfu-popupinfo--get-documentation (car corfu--candidates))))
    (delete-region (- (point) 4) (point))
    (let ((this-command 'delete-backward-char)) (corfu--post-command))
    (should completion-in-region-mode)
    (let ((corfu-popupinfo--candidate nil)
          (corfu-popupinfo--function #'corfu-popupinfo--get-documentation)
          hidden)
      (cl-letf (((symbol-function 'corfu-popupinfo--visible-p) (lambda (&optional _) t))
                ((symbol-function 'corfu-popupinfo--hide) (lambda () (setq hidden t))))
        (corfu-popupinfo--show (car corfu--candidates)))
      (should hidden)
      (should completion-in-region-mode))))

(ert-deftest emmet2-capf-single-line-is-not-truncated-or-documented ()
  (emmet2-test--with-capf (concat "p{" (make-string 140 ?x) "}")
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidate (car (all-completions (buffer-string) (nth 2 data))))
           (row (car (funcall (plist-get props :affixation-function) (list candidate)))))
      (should (equal (cadr row) (concat "<p>" (make-string 140 ?x) "</p>")))
      (should-not (funcall (plist-get props :company-doc-buffer) candidate)))))

(ert-deftest emmet2-capf-choices-are-lazy-and-reused-per-revision ()
  (emmet2-test--with-css-completion "ta"
    (let ((expand (symbol-function 'emmet2-expand-analysis)) (calls 0))
      (cl-letf (((symbol-function 'emmet2-expand-analysis)
                 (lambda (analysis) (cl-incf calls) (funcall expand analysis))))
        (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data)))
          (completion-metadata "ta" table nil)
          (should (= calls 0))
          (let ((candidates (all-completions "ta" table)))
            (should (> (length candidates) 1))
            (let ((expanded calls))
              (funcall (plist-get props :affixation-function) candidates)
              (all-completions "ta" table)
              (dolist (candidate candidates)
                (funcall (plist-get props :company-doc-buffer) candidate))
              (should (= expanded calls)))))))))

(ert-deftest emmet2-capf-css-keywords-through-corfu ()
  (dolist (case '(("tac" 3 "text-align: center;")
                  ("dn" 2 "display: none;") ("dn" 3 nil)
                  ("posr" 3 "position: relative;")))
    (with-temp-buffer
      (css-mode) (insert ".a{" (car case) "}") (backward-char) (emmet2-mode 1)
      (let ((corfu-auto-prefix (nth 1 case)) (corfu-auto-trigger nil)
            (corfu-on-exact-match 'show) (corfu-preview-current nil)
            (completion-styles '(basic partial-completion))
            (completion-category-defaults nil) (completion-category-overrides nil)
            (last-command-event (aref (car case) (1- (length (car case))))) shown)
        (cl-letf (((symbol-function 'corfu--candidates-popup) (lambda (&rest _) (setq shown t)))
                  ((symbol-function 'corfu--popup-hide) #'ignore)
                  ((symbol-function 'corfu--protect) #'funcall))
          (unwind-protect
              (progn
                (corfu-auto--complete-deferred)
                (should (eq (not (null shown)) (not (null (nth 2 case)))))
                (when shown (corfu-insert))
                (should (equal (buffer-string) (concat ".a{" (or (nth 2 case) (car case)) "}"))))
            (when completion-in-region-mode (corfu-quit))))))))

(ert-deftest emmet2-capf-rejects-every-stale-source ()
  (dolist (change '(outside delete-restore point mode narrow disabled options indent host buffer))
    (ert-info ((format "%s" change))
      (emmet2-test--with-capf "<main>ul>li*2</main>"
        (goto-char 14)
        (let* ((data (emmet2-capf)) (table (nth 2 data))
               (exit (plist-get (nthcdr 3 data) :exit-function))
               (abbr "ul>li*2"))
          (should (equal (all-completions abbr table) (list abbr)))
          (pcase change
            ('outside (save-excursion (goto-char (point-min)) (insert "x")))
            ('delete-restore (delete-char -1) (insert "2"))
            ('point (backward-char))
            ('mode (text-mode))
            ('narrow (narrow-to-region 8 14))
            ('disabled (emmet2-mode -1))
            ('options (setq-local emmet2-markup-variant "solid"))
            ('indent (setq-local web-mode-markup-indent-offset 9))
            ('host
             (let ((tick (buffer-chars-modified-tick)))
               (setq-local web-mode-content-type "jsx")
               (should (= tick (buffer-chars-modified-tick))))))
          (cl-flet ((reject ()
                      (let ((before (buffer-string)) (position (point)))
                        (should-not (all-completions abbr table))
                        (funcall exit abbr 'finished)
                        (should (equal (buffer-string) before))
                        (should (= position (point))))))
            (if (eq change 'buffer)
                (with-temp-buffer (insert "<main>ul>li*2</main>") (web-mode) (goto-char 14) (reject))
              (reject))))))))

(ert-deftest emmet2-capf-exit-status-and-candidate-guard ()
  (dolist (status '(exact sole nil cancelled))
    (emmet2-test--with-capf "ul>li*3"
      (let ((exit (plist-get (nthcdr 3 (emmet2-capf)) :exit-function)))
        (funcall exit "ul>li*3" status)
        (funcall exit "div.card" 'finished)
        (should (equal (buffer-string) "ul>li*3"))))))

(ert-deftest emmet2-capf-backend-failure-and-source-change ()
  (dolist (failure '(parse quit backend source))
    (emmet2-test--with-capf "ul>li*3"
      (let ((attempts 0))
        (cl-letf (((symbol-function 'emmet2-expand-analysis)
                   (lambda (_)
                     (cl-incf attempts)
                     (pcase failure
                       ('parse (signal 'emmet2-parse-error '("invalid" 0)))
                       ('quit (signal 'quit nil))
                       ('backend (signal 'emmet2-backend-error '("Expansion deadline exceeded")))
                       ('source (insert "4") (emmet2-result-create "unsafe"))))))
          (if (eq failure 'quit)
              (should (eq (condition-case nil (all-completions "ul>li*3" table)
                            (quit 'cancelled)) 'cancelled))
            ;; A failed session never retries the expansion or signals to the frontend.
            (should-not (all-completions "ul>li*3" table))
            (should-not (all-completions "ul>li*3" table))
            (should (= attempts 1)))
          (should (equal (buffer-string) (if (eq failure 'source) "ul>li*34" "ul>li*3"))))))))

(ert-deftest emmet2-capf-mode-registration-and-command-isolation ()
  (let ((global completion-at-point-functions))
    (with-temp-buffer
      (insert "div") (web-mode)
      (let ((other (lambda () (error "Other capf must not run"))))
        (setq-local completion-at-point-functions (list other))
        (emmet2-mode 1) (emmet2-mode 1)
        (should (equal completion-at-point-functions (list #'emmet2-capf other)))
        (emmet2-test--complete-first)
        (should (equal (buffer-string) "<div></div>"))
        (should (equal completion-at-point-functions (list #'emmet2-capf other)))
        (erase-buffer)
        (should-error (emmet2-complete) :type 'user-error)
        (emmet2-mode -1)
        (should (equal completion-at-point-functions (list other)))))
    (should (equal completion-at-point-functions global))))

(ert-deftest emmet2-capf-builtin-css-command-shares-automatic-admission ()
  (dolist (mode '(css-mode css-ts-mode scss-mode))
    (dolist (source '(".a { m10│ }" ".a { /* layout */ p[1px│ 2px] }"
                      ".a { w(2)│ }" ".a { unknown│ }" ".a { m$gap│ }"
                      "m10│" ".a { color: m10│ }" ".a { future-prop:foo│ }"
                      ".a { /* m10│ */ }" ".a { content: 'm10│' }"))
      (ert-info ((format "%s %s" mode source))
        (with-temp-buffer
          (insert source) (cl-letf (((symbol-function 'display-warning) #'ignore)) (funcall mode))
          (search-backward "│") (delete-char 1)
          (let* ((before (buffer-string)) (position (point))
                 (auto (emmet2-capf))
                 (input (and auto (buffer-substring-no-properties (nth 0 auto) (nth 1 auto))))
                 (choices (and auto (all-completions input (nth 2 auto))))
                 (results (mapcar (lambda (choice) (plist-get (get-text-property 0 'emmet2--choice choice) :result))
                                  choices))
                 requested
                 (completion-in-region-function
                  (lambda (beg end table &optional _predicate)
                    (setq requested t)
                    (should (= beg (nth 0 auto)))
                    (should (= end (nth 1 auto)))
                    (should (equal results
                                   (mapcar (lambda (choice)
                                             (plist-get (get-text-property 0 'emmet2--choice choice) :result))
                                           (all-completions input table))))
                    t)))
            (if choices
                (progn (emmet2-complete) (should requested))
              (should-error (emmet2-complete) :type 'user-error)
              (should-not requested))
            (should (equal (buffer-string) before))
            (should (= (point) position))))))))

(ert-deftest emmet2-capf-explicit-command-warms-and-skips-automatic-gates ()
  (with-temp-buffer
    (insert "const A=(<main>ul>li*2</main>);") (tsx-ts-mode) (search-backward "</main>")
    (let ((completion-in-region-function (lambda (_beg _end table &optional _pred)
                                           (should (test-completion "ul>li*2" table)) t)))
      (should-not (emmet2-capf))
      (emmet2-complete)
      (should (emmet2-capf))))
  ;; An explicit request also offers positions automatic completion leaves
  ;; ambiguous, as the retired expansion command did.
  (with-temp-buffer
    (insert "const A=()=>ul>li*2;") (tsx-ts-mode) (backward-char)
    (emmet2-context-analyze)
    (should-not (emmet2-capf))
    (emmet2-test--complete-first)
    (should (string-match-p "<ul>" (buffer-string))))
  (with-temp-buffer
    (insert "<p>A div here</p>") (web-mode) (emmet2-mode 1)
    (search-backward " here")
    (should-not (emmet2-capf))
    (emmet2-test--complete-first)
    (should (equal (buffer-string) "<p>A <div></div> here</p>")))
  (with-temp-buffer
    (insert "const A=(<main>ul>li*2</main>);") (tsx-ts-mode) (search-backward "</main>")
    (cl-letf (((symbol-function 'treesit-language-available-p) (lambda (&rest _) nil)))
      (should-not (emmet2-capf))
      (should-error (emmet2-complete) :type 'user-error))))

(ert-deftest emmet2-capf-corfu-acceptance-matrix-and-middle-point ()
  (dolist (configuration '(((basic partial-completion emacs22) nil)
                           ((partial-completion basic) nil)
                           ((partial-completion) nil)
                           ((basic partial-completion emacs22) ((emmet2 (styles partial-completion))))))
    (dolist (exact '(nil show insert quit))
      (dolist (command '(completion-at-point emmet2-complete))
        (dolist (middle '(nil t))
          (should (eq (cadr (emmet2-test--completion-session
                             (car configuration) (cadr configuration) exact nil nil nil t nil middle command))
                      'finished)))))))

(ert-deftest emmet2-capf-corfu-prompt-and-selection ()
  (dolist (select '(nil t))
    (let ((result
           (emmet2-test--completion-session
            '(basic partial-completion) nil nil nil nil nil nil 'prompt nil nil
            (lambda ()
              (should (= corfu--index -1))
              (when select (corfu-next))
              (corfu-insert)
              (should (equal (buffer-string)
                             (if select "<ul>\n    <li></li>\n    <li></li>\n    <li></li>\n</ul>" "ul>li*3")))))))
      (should (eq (cadr result) (and select 'finished))))))

(ert-deftest emmet2-capf-corfu-typing-refreshes-without-hiding ()
  (dolist (action '(insert delete))
    (save-window-excursion
      (let ((result
             (emmet2-test--completion-session
              '(basic partial-completion) nil nil nil "m1" nil nil nil nil nil
              (lambda ()
                (set-window-buffer (selected-window) (current-buffer))
                (let* ((old-table (nth 2 completion-in-region--data))
                       (old-candidate (car corfu--candidates))
                       (exit (plist-get (nth 4 completion-in-region--data) :exit-function)))
                  (if (eq action 'insert) (insert "4") (delete-char -1))
                  (let ((before (buffer-string)))
                    (cl-letf (((symbol-function 'corfu--popup-hide)
                               (lambda () (ert-fail "Typing must not hide the popup"))))
                      (let ((this-command (if (eq action 'insert) 'self-insert-command 'delete-backward-char)))
                        (corfu--post-command)))
                    (should completion-in-region-mode)
                    (should (eq (nth 2 completion-in-region--data) old-table))
                    (funcall exit old-candidate 'finished)
                    (should (equal (buffer-string) before))
                    (should (equal (substring-no-properties (car corfu--candidates))
                                   (if (eq action 'insert) "m14" "m")))))))))
        (should-not (cadr result))))))

(ert-deftest emmet2-capf-corfu-movement-outside-ends-session ()
  (save-window-excursion
    (emmet2-test--completion-session
     '(basic partial-completion) nil nil nil nil nil nil nil nil nil
     (lambda ()
       (set-window-buffer (selected-window) (current-buffer))
       (goto-char (point-min))
       (let ((this-command 'beginning-of-buffer)) (corfu--post-command))
       (should-not completion-in-region-mode)))))

(ert-deftest emmet2-capf-corfu-buffer-switch-and-killed-source ()
  (should-not
   (cadr
    (emmet2-test--completion-session
     '(basic partial-completion) nil nil nil nil nil nil nil nil nil
     (lambda ()
       (let ((source (current-buffer)))
         (with-temp-buffer
           (insert "other buffer")
           ;; Corfu's post-command observer sees the actual buffer change.
           (corfu--post-command)
           (should-not completion-in-region-mode)
           (should (equal (buffer-string) "other buffer")))
         (should (equal (with-current-buffer source (buffer-string)) "ul>li*3")))))))
  (let (captured-table exit)
    (emmet2-test--with-capf "ul>li*3"
      (let ((data (emmet2-capf)))
        (setq captured-table (nth 2 data) exit (plist-get (nthcdr 3 data) :exit-function))))
    (should (functionp captured-table))
    (with-temp-buffer
      (insert "ul>li*3")
      (should-not (all-completions "ul>li*3" captured-table))
      (funcall exit "ul>li*3" 'finished)
      (should (equal (buffer-string) "ul>li*3")))))

(ert-deftest emmet2-capf-auto-threshold-does-not-expand ()
  (with-temp-buffer
    (insert ".a{m1}") (css-mode) (backward-char) (emmet2-mode 1)
    (let ((corfu-auto-prefix 3) (corfu-auto-trigger nil) (last-command-event ?1))
      (cl-letf (((symbol-function 'emmet2-capf--choices)
                 (lambda (&rest _) (ert-fail "Below-threshold candidate must stay lazy")))
                ((symbol-function 'corfu--protect) #'funcall))
        (corfu-auto--complete-deferred)
        (should-not completion-in-region-mode)
        (should (equal (buffer-string) ".a{m1}"))))))

(ert-deftest emmet2-capf-frontend-free-acceptance-and-undo ()
  (emmet2-test--with-capf "ul>li*3"
    (buffer-enable-undo)
    (let ((completion-styles '(partial-completion))
          (completion-category-defaults nil) (completion-category-overrides nil)
          (completion-in-region-function #'completion--in-region)
          (completion-cycle-threshold nil))
      (completion-at-point)
      (should (string-prefix-p "<ul>" (buffer-string)))
      (undo 1)
      (should (equal (buffer-string) "ul>li*3")))))

(ert-deftest emmet2-capf-read-only-and-invalid-syntax ()
  (emmet2-test--with-capf "ul>li*3"
    (setq buffer-read-only t)
    (should-not (emmet2-capf)))
  (with-temp-buffer
    (insert ".a{p(1}") (css-mode) (backward-char)
    (let ((table (nth 2 (emmet2-capf))))
      (should table)
      (should-not (all-completions "p(1" table)))))

(provide 'emmet2-capf-test)
;;; emmet2-capf-test.el ends here
