;;; emmet2-engine-stylesheet-test.el --- Native CSS contracts -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'emmet2-engine-stylesheet)

(ert-deftest emmet2-stylesheet-canonical-names-and-keywords ()
  (dolist (case '(("inset-block10" . "inset-block: 10px;") ("max-inline-size:" . "max-inline-size: ;")
                  ("display" . "display: ;") ("top-a" . "top: auto;") ("margin0-a" . "margin: 0 auto;")
                  ("border1#2s" . "border: 1px #222 solid;") ("padding$a$b$c" . "padding: $a $b $c;")
                  ;; Unmatched literals and unknown names stay as written; the
                  ;; extension layer chooses properties before calling the core.
                  ("top-zz" . "top: zz;") ("m10" . "m: 10px;") ("unknown-a" . "unknown: a;")))
    (ert-info ((car case))
      (should (equal (plist-get (emmet2-engine-stylesheet-expand (car case)) :text) (cdr case))))))

(ert-deftest emmet2-stylesheet-canonical-property-negative-values ()
  (dolist (case '(("inset-block-10" . "inset-block: -10px;")
                  ("margin-left-10" . "margin-left: -10px;")
                  ("inset-block-end-.5" . "inset-block-end: -0.5rem;")
                  ("margin-10+inset-inline-start-2" . "margin: -10px;\ninset-inline-start: -2px;")))
    (ert-info ((car case))
      (should (equal (plist-get (emmet2-engine-stylesheet-expand (car case)) :text) (cdr case))))))

(ert-deftest emmet2-stylesheet-units-colors-and-unitless-properties ()
  (dolist (case '(("margin10" . "margin: 10px;") ("margin.5" . "margin: 0.5rem;")
                  ("margin1e" . "margin: 1em;") ("margin1p" . "margin: 1%;") ("margin1x" . "margin: 1ex;")
                  ("margin1r" . "margin: 1rem;") ("margin0" . "margin: 0;") ("z-index10" . "z-index: 10;")
                  ("line-height1.5" . "line-height: 1.5;") ("opacity.5" . "opacity: 0.5;")
                  ("color#f" . "color: #fff;") ("color#fc0" . "color: #fc0;") ("color#3.5" . "color: rgba(51, 51, 51, 0.5);")
                  ("background-color#t" . "background-color: transparent;") ("padding1-2" . "padding: 1px 2px;")
                  ("margin10!" . "margin: 10px !important;")))
    (ert-info ((car case))
      (should (equal (plist-get (emmet2-engine-stylesheet-expand (car case)) :text) (cdr case))))))

(ert-deftest emmet2-stylesheet-numeric-properties-keep-unitless-values ()
  (dolist (case '(("order-1" . "order: -1;")
                  ("column-count2" . "column-count: 2;")
                  ("grid-row-start2" . "grid-row-start: 2;")
                  ("grid-column-end-1" . "grid-column-end: -1;")
                  ("grid-column1/3" . "grid-column: 1 / 3;")
                  ("animation-iteration-count1.5" . "animation-iteration-count: 1.5;")
                  ("border-image-slice30" . "border-image-slice: 30;")
                  ("fill-opacity.5" . "fill-opacity: 0.5;")
                  ("flood-opacity.5" . "flood-opacity: 0.5;")
                  ("stop-opacity.5" . "stop-opacity: 0.5;")
                  ("stroke-opacity.5" . "stroke-opacity: 0.5;")
                  ("stroke-miterlimit4" . "stroke-miterlimit: 4;")
                  ("font-size-adjust.5" . "font-size-adjust: 0.5;")
                  ("shape-image-threshold.5" . "shape-image-threshold: 0.5;")
                  ("scale2" . "scale: 2;")
                  ("aspect-ratio2" . "aspect-ratio: 2;")
                  ("aspect-ratio16/9" . "aspect-ratio: 16 / 9;")
                  ("orphans2" . "orphans: 2;")
                  ("widows2" . "widows: 2;")
                  ("math-depth2" . "math-depth: 2;")
                  ("line-clamp3" . "line-clamp: 3;")
                  ("max-lines3" . "max-lines: 3;")
                  ("hyphenate-limit-chars3" . "hyphenate-limit-chars: 3;")
                  ("initial-letter2" . "initial-letter: 2;")
                  ("mask-border-slice20" . "mask-border-slice: 20;")
                  ("reading-order2" . "reading-order: 2;")
                  ("text-combine-upright:digits2" . "text-combine-upright: digits 2;")
                  ("counter-increment:chapter-2" . "counter-increment: chapter -2;")
                  ("font-feature-settings\"liga\"1" . "font-feature-settings: \"liga\" 1;")
                  ("font-variation-settings\"wght\"400" . "font-variation-settings: \"wght\" 400;")
                  ;; Authored units and properties admitting lengths keep their policy.
                  ("fill-opacity50p" . "fill-opacity: 50%;")
                  ("line-height1.5e" . "line-height: 1.5em;")
                  ("border-image-width2" . "border-image-width: 2px;")
                  ("tab-size4" . "tab-size: 4px;")))
    (ert-info ((car case))
      (should (equal (plist-get (emmet2-engine-stylesheet-expand (car case)) :text) (cdr case))))))

(ert-deftest emmet2-stylesheet-independent-fields-and-unicode ()
  (dolist (case '(("color+background" (:text "color: ;\nbackground: ;" :fields ((7 7 1 "") (21 21 2 "")) :cursor 7))
                  ("padding${2:😀}-${1:x}-${2:😀}-${1:y}+margin${1:z}"
                   (:text "padding: 😀 x 😀 y;\nmargin: z;"
                          :fields ((9 10 3 "😀") (11 12 1 "x") (13 14 3 "😀") (15 16 2 "y") (26 27 4 "z")) :cursor 11))
                  ("margin${0}${0}" (:text "margin: ;" :fields ((8 8 1 "") (8 8 2 "")) :cursor 8))
                  ("padding${9007199254740992:x}-${9007199254740993:x}"
                   (:text "padding: x x;" :fields ((9 10 1 "x") (11 12 1 "x")) :cursor 9))))
    (ert-info ((car case))
      (should (equal (emmet2-engine-stylesheet-expand (car case)) (cadr case))))))

(ert-deftest emmet2-stylesheet-js-numeric-rounding ()
  (dolist (case '(("margin-0.0" . "margin: 0;")
                  ("margin.03125" . "margin: 0.0313rem;")
                  ("margin-.03125" . "margin: -0.0313rem;")
                  ("margin-.00001" . "margin: -0rem;")
                  ("margin1000000000000000000000" . "margin: 1e+21px;")
                  ;; The pinned formatter trims trailing exponent zeroes too.
                  ("margin1000000000000000000000000000000" . "margin: 1e+3px;")))
    (should (equal (plist-get (emmet2-engine-stylesheet-expand (car case)) :text) (cdr case)))))

(ert-deftest emmet2-stylesheet-errors-retain-reference-boundary ()
  ;; These tokenizer failures lack a position and are not parse-error goldens.
  (dolist (input '(":" "-" "," ":-" "+:"))
    (should (equal (should-error (emmet2-engine-stylesheet-expand input) :type 'emmet2-backend-error)
                   '(emmet2-backend-error "Unexpected token"))))
  (should (equal (emmet2-engine-stylesheet-expand ":+") '(:text "" :fields nil :cursor 0)))
  (dolist (case '(("ct\"😀\"+m)" "Unexpected bracket" 7)
                  ("ct\"😀\"+m[" "Unexpected character" 7)
                  ("ct\"😀\"+m10 " "Unexpected token" 9)))
    (should (equal (cdr (should-error (emmet2-engine-stylesheet-expand (car case)) :type 'emmet2-parse-error))
                   (cdr case)))))

(ert-deftest emmet2-stylesheet-results-are-fresh-and-the-index-immutable ()
  (let ((before (prin1-to-string emmet2-css-search--index))
        (input "transform:scale3d(1,2,3)+margin.5+border1#2s") first)
    (setq first (emmet2-engine-stylesheet-expand input))
    (dolist (abbreviation '("border" "color+background" "padding$a$b$c" "top-a" "border${1:solid}"))
      (emmet2-engine-stylesheet-expand abbreviation))
    (let* ((result (emmet2-engine-stylesheet-expand "border${1:solid}"))
           (default (nth 3 (car (plist-get result :fields)))))
      (aset default 0 ?X)
      (should (equal (plist-get (emmet2-engine-stylesheet-expand "border${1:solid}") :text) "border: solid;")))
    (let ((text (plist-get (emmet2-engine-stylesheet-expand "top-a") :text)))
      (aset text 5 ?X)
      (should (equal (plist-get (emmet2-engine-stylesheet-expand "top-a") :text) "top: auto;")))
    (should (equal first (emmet2-engine-stylesheet-expand input)))
    (should (equal before (prin1-to-string emmet2-css-search--index)))))

(ert-deftest emmet2-stylesheet-pure-and-deadline-bound ()
  (let ((exec-path nil))
    (cl-letf (((symbol-function 'make-process) (lambda (&rest _) (error "Unexpected process")))
              ((symbol-function 'insert-file-contents) (lambda (&rest _) (error "Unexpected file read"))))
      (with-temp-buffer
        (insert "unchanged") (goto-char 3)
        (let ((tick (buffer-chars-modified-tick)))
          (emmet2-engine-stylesheet-expand "margin10+padding.5+border1#2s+z-index5+font-size16")
          (should (equal (buffer-string) "unchanged"))
          (should (= (point) 3))
          (should (= tick (buffer-chars-modified-tick)))))))
  (let ((emmet2-engine--deadline 0))
    (should-error (emmet2-engine-stylesheet-expand "margin") :type 'emmet2-backend-error))
  (let ((emmet2-engine--timeout 0.001))
    (should-error (emmet2-engine-stylesheet-expand (apply #'concat (make-list 20000 "margin+")))
                  :type 'emmet2-backend-error))
  (dolist (arguments '((nil) ("margin" :preset html) ("margin" :indent nil) ("margin" :base-indent 2)))
    (should-error (apply #'emmet2-engine-stylesheet-expand arguments) :type 'emmet2-error)))

(provide 'emmet2-engine-stylesheet-test)
;;; emmet2-engine-stylesheet-test.el ends here
