;;; emmet2-markup-integration-test.el --- Markup through editor boundaries -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-insert-test)
(require 'emmet2-capf-test)
(require 'emmet2-preview-test)

(ert-deftest emmet2-markup-command-completion-preview-and-yas ()
  (unwind-protect
      (dolist (case '((web-mode "<main>ul>li│*2</main>" nil)
                      (web-mode "<main>.card>span{${1:😀} ${1:😀}}│</main>" "solid")
                      (tsx-ts-mode "const A=(<main>ul>li│*2</main>);" nil)
                      (tsx-ts-mode "const A=(<main>.card>span{${1:😀} ${1:😀}}│</main>);" "solid")
                      (js-mode "const A=(<main>.card│</main>);" nil)
                      (web-mode "<main>p>lorem5+span{${1:😀}}│</main>" nil)))
        (dolist (yas '(nil t))
          (dolist (completion '(nil t))
            (ert-info ((format "%S yas=%s completion=%s" case yas completion))
              (with-temp-buffer
                (insert (nth 1 case)) (search-backward "│") (delete-char 1)
                (let ((position (point)))
                  (setq buffer-file-name (if (eq (car case) 'web-mode) "/tmp/emmet2.html" "/tmp/emmet2.tsx"))
                  (funcall (car case)) (goto-char position))
                (setq-local indent-tabs-mode nil emmet2-markup-variant (nth 2 case)
                            emmet2-css-modules-object "styles" emmet2-class-names-constructor "cx")
                (emmet2-mode 1)
                (when yas (yas-minor-mode 1))
                (buffer-enable-undo)
                (let* ((this-command 'emmet2-expand)
                       (analysis (emmet2-context-analyze)) (abbr (plist-get analysis :abbr))
                       (beg (plist-get analysis :beg)) (end (plist-get analysis :end))
                       (before (buffer-string)) (result (emmet2--expand-analysis analysis))
                       (expand (symbol-function 'emmet2--expand-analysis)) (calls 0)
                       (yas-indent-line 'auto) (yas-wrap-around-region t) (exits 0))
                  (add-hook 'yas-after-exit-snippet-hook (lambda () (cl-incf exits)) nil t)
                  (let ((hooks (copy-sequence yas-after-exit-snippet-hook)))
                    (cl-letf (((symbol-function 'emmet2--expand-analysis)
                               (lambda (value) (cl-incf calls) (funcall expand value)))
                              ((symbol-function 'indent-region) (lambda (&rest _) (error "Second indentation"))))
                      (if (not completion) (emmet2-expand)
                        (let* ((data (emmet2-capf)) (props (nthcdr 3 data)))
                          (should data)
                          (should (equal (all-completions abbr (nth 2 data)) (list abbr)))
                          (with-current-buffer (funcall (plist-get props :company-doc-buffer) abbr)
                            (should (equal (buffer-substring-no-properties (point-min) (point-max))
                                           (plist-get result :text))))
                          (funcall (plist-get props :exit-function) abbr 'finished)))
                      (should (= calls 1)))
                    (should (equal (buffer-string) (concat (substring before 0 (1- beg))
                                                          (plist-get result :text) (substring before (1- end)))))
                    (should (= (point) (+ beg (plist-get result :cursor))))
                    (when (and yas (plist-get result :fields))
                      (should (yas-active-snippets))
                      (yas-exit-all-snippets)
                      (should (= exits 1))
                      (should (= (point) (+ beg (length (plist-get result :text))))))
                    (should (eq yas-indent-line 'auto))
                    (should yas-wrap-around-region)
                    (should (equal hooks yas-after-exit-snippet-hook))
                    (undo-only 1)
                    (should (equal (buffer-string) before))
                    (should-not (yas-active-snippets)))))))))
    (emmet2-preview-clear)))

(provide 'emmet2-markup-integration-test)
;;; emmet2-markup-integration-test.el ends here
