;;; emmet2-css-data-test.el --- Shared CSS query contracts -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'ert)
(require 'emmet2-css-data)

(ert-deftest emmet2-css-data-searches-real-names-and-scoped-values ()
  (should (equal (caar (emmet2-css-data-query 'property :query "ins")) "inset"))
  (should (assoc "inline-size" (emmet2-css-data-query 'property :query "size")))
  (should (assoc "inline-block" (emmet2-css-data-query 'value :property "DISPLAY" :query "ib")))
  (should-not (assoc "red" (emmet2-css-data-query 'value :property "display")))
  (should (assoc "red" (emmet2-css-data-query 'value :property "color")))
  (should-not (assoc "flex" (emmet2-css-data-query 'value :property "color")))
  (should (assoc "calc()" (emmet2-css-data-query 'value :property "width")))
  (should (assoc "inherit" (emmet2-css-data-query 'value :property "unknown-property")))
  (should (stringp (cdr (assoc "display" (emmet2-css-data-query 'property))))))

(ert-deftest emmet2-css-data-respects-descriptors-and-vendor-policy ()
  (dolist (name '("font-display" "src" "unicode-range"))
    (should-not (assoc name (emmet2-css-data-query 'property)))
    (should (assoc name (emmet2-css-data-query 'property :at-rule "@font-face"))))
  (should (assoc "font-display" (emmet2-css-data-query 'property :at-rule "@FONT-FACE")))
  (should (assoc "swap" (emmet2-css-data-query 'value :property "font-display" :at-rule "@font-face")))
  (should-not (assoc "swap" (emmet2-css-data-query 'value :property "font-display")))
  (should (assoc "@media" (emmet2-css-data-query 'at-rule)))
  (should (assoc ":hover" (emmet2-css-data-query 'pseudo)))
  (should (= 579 (length (emmet2-css-data-query 'property))))
  (should (> (length (emmet2-css-data-query 'property :vendor t)) 579))
  (should-error (emmet2-css-data-query 'unknown)))

(ert-deftest emmet2-css-data-properties-can-also-serve-as-descriptors ()
  (dolist (name '("font-family" "font-feature-settings" "font-stretch" "font-style"
                  "font-weight" "font-variation-settings" "speak-as"))
    (should (assoc name (emmet2-css-data-query 'property))))
  (should (assoc "font-family" (emmet2-css-data-query 'property :at-rule "@font-face")))
  (dolist (rule '(nil "@font-face"))
    (should (assoc "italic" (emmet2-css-data-query 'value :property "font-style" :query "ita" :at-rule rule)))
    (should (assoc "bold" (emmet2-css-data-query 'value :property "font-weight" :query "bol" :at-rule rule)))))

(ert-deftest emmet2-css-data-is-buffer-independent-and-retains-no-query-state ()
  (let ((expected (emmet2-css-data-query 'value :property "display" :query "ib")))
    (with-temp-buffer
      (insert "unrelated text, without a stylesheet mode")
      (let ((text (buffer-string)) (position (point)) (tick (buffer-chars-modified-tick)))
        (should (equal expected (emmet2-css-data-query 'value :property "display" :query "ib")))
        (should (= position (point)))
        (should (= tick (buffer-chars-modified-tick)))
        (should (equal text (buffer-string)))))
    (let ((result (emmet2-css-data-query 'value :property "display" :query "ib")))
      (setcar (car result) "host-owned replacement")
      (setcdr (car result) "host documentation")
      (should (equal expected (emmet2-css-data-query 'value :property "display" :query "ib"))))))

(ert-deftest emmet2-css-data-compact-index-agrees-with-shared-queries ()
  (dolist (mapping '((property . emmet2-css-search-property-names) (at-rule . emmet2-css-search-at-rules)
                     (pseudo . emmet2-css-search-pseudos)))
    (should (equal (mapcar #'car (emmet2-css-data-query (car mapping))) (funcall (cdr mapping))))))

(ert-deftest emmet2-css-data-values-share-complete-keyword-sets ()
  (dolist (case '(("border-style" "solid") ("border" "solid")
                  ("border-width" "thin") ("border-width" "thick")
                  ("color" "orange") ("color" "rebeccapurple")
                  ("background" "repeat") ("background-image" "conic-gradient()")))
    (ert-info ((format "%S" case))
      (should (assoc (cadr case) (emmet2-css-data-query 'value :property (car case))))))
  (should-not (assoc "auto-fill" (emmet2-css-data-query 'value :property "grid-template-columns")))
  (should-not (assoc "InfoText" (emmet2-css-data-query 'value :property "color")))
  (should (stringp (cdr (assoc "flex" (emmet2-css-data-query 'value :property "display")))))
  ;; Restriction-derived values remain available for vendor and obsolete names.
  (dolist (property '("-webkit-text-fill-color" "scrollbar-face-color"))
    (should (assoc "orange" (emmet2-css-data-query 'value :property property :vendor t))))
  (let ((values (emmet2-css-data-query 'value :property "color")))
    (setcar (assoc "orange" values) "host-owned")
    (should (assoc "orange" (emmet2-css-data-query 'value :property "color")))))

(ert-deftest emmet2-css-data-descriptors-do-not-inherit-property-defaults ()
  (should (equal (mapcar #'car (emmet2-css-data-query 'value :property "inherits" :at-rule "@property"))
                 '("env()" "false" "true")))
  (dolist (case '(("font-display" "@font-face") ("font-style" "@font-face")
                  ("initial-value" "@property") ("inherits" "@PROPERTY")
                  ("additive-symbols" "@counter-style") ("negative" "@counter-style")
                  ("pad" "@counter-style") ("prefix" "@counter-style")
                  ("suffix" "@counter-style") ("symbols" "@counter-style")))
    (let ((values (emmet2-css-data-query 'value :property (car case) :at-rule (cadr case))))
      (should (assoc "env()" values))
      (dolist (name '("inherit" "initial" "unset" "revert" "revert-layer" "var()"))
        (should-not (assoc name values)))))
  (let ((values (emmet2-css-data-query 'value :property "symbols" :at-rule "@counter-style")))
    (should (assoc "linear-gradient()" values))
    (should (assoc "url()" values)))
  (dolist (rule '(nil "@media"))
    (let ((values (emmet2-css-data-query 'value :property "font-style" :at-rule rule)))
      (should (assoc "italic" values))
      (should (assoc "inherit" values))
      (should (assoc "var()" values)))))

(provide 'emmet2-css-data-test)
;;; emmet2-css-data-test.el ends here
