;;; emmet2-capf-test.el --- Completion safety and lifecycle -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-capf-contract-test)
(require 'typescript-ts-mode)
(require 'yasnippet)
(require 'corfu-popupinfo)

(defmacro emmet2-test--with-css-completion (input &rest body)
  "Run BODY in a displayed CSS buffer containing INPUT, using real Corfu."
  (declare (indent 1) (debug t))
  `(save-window-excursion
     (with-temp-buffer
       (set-window-buffer (selected-window) (current-buffer))
       (css-mode) (insert ".a{" ,input "}") (backward-char)
       (emmet2-mode 1) (buffer-enable-undo)
       (let ((completion-styles '(basic partial-completion))
             (completion-category-defaults nil) (completion-category-overrides nil)
             (corfu-auto-prefix 1) (corfu-auto-trigger nil)
             (corfu-on-exact-match 'show) (corfu-preview-current nil)
             (last-command-event ?a))
         (cl-letf (((symbol-function 'corfu--popup-show) #'ignore)
                   ((symbol-function 'corfu--popup-hide) #'ignore)
                   ((symbol-function 'corfu--protect) #'funcall))
           (unwind-protect (progn ,@body)
             (when completion-in-region-mode (corfu-quit))))))))

(ert-deftest emmet2-capf-confidence-and-host-gates ()
  (dolist (case '((web-mode "div│" nil) (web-mode "custom-element│" nil)
                  (web-mode "a:link│" nil) (web-mode "!│" t)
                  (web-mode "ul>li*2│" t) (web-mode "div.card│" t)
                  (web-mode "<p>This is the end.│</p>" nil) (web-mode "<p>See e.g.│</p>" nil)
                  (web-mode "ul>li.│" t)
                  (tsx-ts-mode "const A=(<p>Hello world.│</p>);" nil)
                  (web-mode "<div title='ul>li*2│'></div>" nil)
                  (web-mode "<!-- ul>li*2│ -->" nil)
                  (css-mode ".a{margin│}" nil) (css-mode ".a{m│}" t)
                  (css-mode ".a{tac│}" t) (css-mode ".a{dn│}" t)
                  (scss-mode ".a{posr│}" t) (css-mode ".a{wf│}" t)
                  (css-mode ".a{all│}" nil) (css-mode ".a{unknownword│}" nil)
                  (css-mode ".a{display│}" nil) (css-mode ".a{ta│}" t)
                  (css-mode ".a{color:tac│}" nil) (css-mode "tac│" nil)
                  (css-mode ".a{/* tac│ */}" nil) (css-mode ".a{content: 'tac│'}" nil)
                  (css-mode ".a{m1│}" t) (css-mode ".a{mA│}" t)
                  (css-mode ".a{c#fff│}" t) (css-mode ".a{p!│}" t)
                  (css-mode ".a{p[1px]│}" t) (css-mode ".a{p(1 + 2)│}" t)
                  (css-mode ".a{m,p│}" t) (css-mode ".a{c+bg│}" t)
                  (css-mode ".a{color: m1│}" nil) (css-mode ".card│" nil)
                  (css-mode ".a{display:fl│}" nil) (css-mode ".a{--accent:re│}" nil)
                  (css-mode ".a{future-prop:foo│}" nil) (css-mode ".a{d:n│}" nil)
                  (css-mode ".a{_:hv│}" t) (css-mode ".a{button::be│}" t)
                  (css-mode "@│" nil) (css-mode "@md│" t)
                  (css-mode ":│" nil) (css-mode "_:hv│" t)
                  (css-mode "::b│" t) (css-mode "@media m1│" nil)
                  (fundamental-mode "ul>li*2│" nil)
                  (tsx-ts-mode "const A=(<main>ul>li*2│</main>);" t)
                  (tsx-ts-mode "const A=(<main>{items.ma│}</main>);" nil)
                  (tsx-ts-mode "const A=(<main style={{tac│}} />);" t)
                  (tsx-ts-mode "const A=(<main other={{tac│}} />);" nil)
                  (tsx-ts-mode "const A=()=>ul>li*2│;" nil)
                  (tsx-ts-mode "const A=(<main style={{m10│}} />);" t)))
    (ert-info ((format "%S" case))
      (with-temp-buffer
        (insert (nth 1 case))
        (search-backward "│") (delete-char 1)
        (let ((position (point)))
          (funcall (car case)) (goto-char position)
          (emmet2-context--prepare)
          (should (eq (not (null (emmet2-capf))) (nth 2 case))))))))

(ert-deftest emmet2-capf-lazy-results-and-expansion-display ()
  (emmet2-test--with-capf "p{界😀abcdefghijklmnop}*5"
    (let* ((expand (symbol-function 'emmet2--expand-analysis)) (calls 0)
           (data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (abbr (buffer-string)))
      (cl-letf (((symbol-function 'emmet2--expand-analysis)
                 (lambda (analysis) (cl-incf calls) (funcall expand analysis))))
        (should (eq (completion-metadata-get (completion-metadata abbr table nil) 'category) 'emmet2))
        (should (= calls 0))
        (should (equal (all-completions abbr table) (list abbr)))
        (should (test-completion abbr table))
        (should (equal (try-completion abbr table) abbr))
        (let ((row (car (funcall (plist-get props :affixation-function)
                                 (all-completions abbr table)))))
          (should (equal (get-text-property 0 'display (car row)) ""))
          (should (equal (cadr row)
                         (string-join (make-list 5 "<p>界😀abcdefghijklmnop</p>") " ")))
          (should (equal (caddr row) "")))
        (should-not (plist-member props :annotation-function))
        (should (eq (funcall (plist-get props :company-kind) abbr) 'snippet))
        (should-not (plist-member props :company-prefix-length))
        (should (= calls 1))
        (should (equal (buffer-string) abbr))))))

(ert-deftest emmet2-capf-multiline-only-formatted-preview ()
  (unwind-protect
      (dolist (abbr '("m10+p20" "tac"))
        (with-temp-buffer
          (css-mode) (insert ".a{" abbr "}") (backward-char)
          (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
                 (source (buffer-string))
                 (text (if (equal abbr "tac") "text-align: center;"
                         "margin: 10px;\n   padding: 20px;"))
                 (row (car (funcall (plist-get props :affixation-function)
                                    (all-completions abbr (nth 2 data))))))
            (should (equal (all-completions abbr (nth 2 data)) (list abbr)))
            (should (equal (cadr row) (if (equal abbr "tac") text "margin: 10px; padding: 20px;")))
            (if (equal abbr "tac")
                (should-not (funcall (plist-get props :company-doc-buffer) abbr))
              (with-current-buffer (funcall (plist-get props :company-doc-buffer) abbr)
                (should (equal (buffer-substring-no-properties (point-min) (point-max))
                               "margin: 10px;\npadding: 20px;"))
                (should (text-property-not-all (point-min) (point-max) 'face nil))))
            (should (equal (buffer-string) source))
            (funcall (plist-get props :exit-function) abbr 'finished)
            (should (equal (buffer-string) (concat ".a{" text "}"))))))
    (emmet2-preview-clear)))

(ert-deftest emmet2-capf-display-highlights-literal-matches-without-changing-results ()
  (dolist (case '(("tac" "text-align: center;" (0 5 12))
                  ("m10," "margin: 10px;" (0 8 9))
                  ("TAC" "text-align: center;" (0 5 12))
                  ("wf" "width: 100%;" nil)))
    (pcase-let* ((`(,input ,text ,positions) case)
                 (result (emmet2-result-create text))
                 (label (emmet2-capf--display (plist-get result :text) input)))
      (should (equal label text))
      (should (equal (cl-loop for i below (length label)
                              when (get-text-property i 'face label) collect i)
                     positions))
      (should-not (text-property-not-all 0 (length text) 'face nil (plist-get result :text))))))

(ert-deftest emmet2-capf-css-prefix-choices-and-distinct-acceptance ()
  (with-temp-buffer
    (css-mode) (insert ".a{ta}") (backward-char)
    (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
           (candidates (all-completions "ta" table))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (labels (mapcar #'cadr rows)))
      (dolist (text '("text-align: ;" "text-align: left;" "text-align: center;"
                      "text-align: right;" "text-align: justify;" "text-align-last: ;"))
        (should (member text labels)))
      (should (= (length labels) (length (delete-dups (copy-sequence labels)))))
      (should (cl-every (lambda (candidate) (equal candidate "ta")) candidates))
      (let ((selected (nth (cl-position "text-align: right;" labels :test #'equal) candidates)))
        (funcall (plist-get props :exit-function) selected 'finished)
        (should (equal (buffer-string) ".a{text-align: right;}"))))))

(ert-deftest emmet2-capf-background-choices-stay-properties ()
  (emmet2-test--with-css-completion "bg"
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "bg" (nth 2 data)))
           (labels (mapcar #'cadr (funcall (plist-get props :affixation-function) candidates)))
           (index (cl-position "background: none;" labels :test #'equal)))
      (should (numberp index))
      (should-not (cl-some (lambda (label) (string-match-p "{" label)) labels))
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) ".a{background: none;}")))))

(ert-deftest emmet2-capf-corfu-alternative-fields-and-one-undo ()
  (dolist (yas '(nil t))
    (dolist (text '("text-align: right;" "text-align-last: ;"))
      (emmet2-test--with-css-completion "ta"
        (when yas (yas-minor-mode 1))
        (corfu-auto--complete-deferred)
        (should completion-in-region-mode)
        (let* ((candidates corfu--candidates)
               (rows (cdr (corfu--affixate candidates)))
               (index (cl-position text (mapcar #'cadr rows) :test #'equal))
               (this-command 'corfu-insert) (last-command nil))
          (should (> index 0))
          (should (cl-every (lambda (row) (equal (get-text-property 0 'display (car row)) "")) rows))
          (corfu--goto index)
          (corfu-insert)
          (should (equal (buffer-string) (concat ".a{" text "}")))
          (when (equal text "text-align-last: ;")
            (should (eq (not (null (yas-active-snippets))) yas))
            (should (eq (char-after) ?\;)))
          (undo-only 1)
          (should (equal (buffer-string) ".a{ta}"))
          (should-not (yas-active-snippets)))))))

(ert-deftest emmet2-capf-corfu-accepts-latest-revision ()
  (emmet2-test--with-css-completion "m10"
    (corfu-auto--complete-deferred)
    (insert "0")
    (let ((this-command 'self-insert-command)) (corfu--post-command))
    (should completion-in-region-mode)
    (corfu-insert)
    (should (equal (buffer-string) ".a{margin: 100px;}"))
    (undo-only 1)
    (should (equal (buffer-string) ".a{m100}"))))

(ert-deftest emmet2-capf-corfu-comma-retains-choices-and-continues-properties ()
  (dolist (input '("m10" "ta" "m10,p20"))
    (emmet2-test--with-css-completion input
      (corfu-auto--complete-deferred)
      (let ((table (nth 2 completion-in-region--data))
            (labels (mapcar #'cadr (cdr (corfu--affixate corfu--candidates)))))
        (cl-letf (((symbol-function 'corfu--popup-hide)
                   (lambda () (ert-fail "A pending comma must keep the popup visible"))))
          (insert ",")
          (let ((this-command 'self-insert-command)) (corfu--post-command))
          (should completion-in-region-mode)
          (should (eq table (nth 2 completion-in-region--data)))
          (should (equal (mapcar #'cadr (cdr (corfu--affixate corfu--candidates))) labels))
          (insert "ta")
          (let ((this-command 'self-insert-command)) (corfu--post-command))
          (should (> corfu--total 1))
          (should (cl-some (lambda (row) (string-suffix-p "text-align: center;" (cadr row)))
                           (cdr (corfu--affixate corfu--candidates)))))))))

(ert-deftest emmet2-capf-corfu-pending-comma-acceptance-and-undo ()
  (emmet2-test--with-css-completion "m10"
    (corfu-auto--complete-deferred)
    (let* ((props (nth 4 completion-in-region--data))
           (exit (plist-get props :exit-function))
           (old (car corfu--candidates)))
      (insert ",")
      (let ((this-command 'self-insert-command)) (corfu--post-command))
      (funcall exit old 'finished)
      (should (equal (buffer-string) ".a{m10,}"))
      (should completion-in-region-mode)
      (corfu-insert)
      (should (equal (buffer-string) ".a{margin: 10px;}"))
      (undo-only 1)
      (should (equal (buffer-string) ".a{m10,}")))))

(ert-deftest emmet2-capf-corfu-comma-shows-only-the-current-fragment ()
  (emmet2-test--with-css-completion "ovh"
    (corfu-auto--complete-deferred)
    (let ((table (nth 2 completion-in-region--data)))
      (dolist (step '(("," "overflow: hidden;" nil)
                      ("ta" "… text-align: ;" "overflow: hidden;\ntext-align: ;")
                      ("," "… text-align: ;" "overflow: hidden;\ntext-align: ;")
                      ("m10+p20" "… margin: 10px; padding: 20px;"
                       "overflow: hidden;\ntext-align: ;\nmargin: 10px;\npadding: 20px;")))
        (insert (car step))
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should completion-in-region-mode)
        (should (eq table (nth 2 completion-in-region--data)))
        (should (equal (cadar (cdr (corfu--affixate corfu--candidates))) (cadr step)))
        (should (equal (corfu-popupinfo--get-documentation (car corfu--candidates))
                       (nth 2 step)))))))

(ert-deftest emmet2-capf-current-fragment-keeps-complete-insertion-and-undo ()
  (dolist (yas '(nil t))
    (emmet2-test--with-css-completion "c,ta"
      (when yas (yas-minor-mode 1))
      (corfu-auto--complete-deferred)
      (let* ((rows (cdr (corfu--affixate corfu--candidates)))
             (index (cl-position "… text-align: center;" (mapcar #'cadr rows) :test #'equal)))
        (should (numberp index))
        (should (equal (corfu-popupinfo--get-documentation (nth index corfu--candidates))
                       "color: ;\ntext-align: center;"))
        (corfu--goto index)
        (corfu-insert)
        (should (equal (buffer-string) ".a{color: ;\n   text-align: center;}"))
        (should (eq (char-after) ?\;))
        (should (eq (not (null (yas-active-snippets))) yas))
        (undo-only 1)
        (should (equal (buffer-string) ".a{c,ta}"))
        (should-not (yas-active-snippets))))))

(ert-deftest emmet2-capf-current-fragment-preview-includes-confirmed-properties ()
  (dolist (case '(("ovh,ta" "… text-align: ;" "overflow: hidden;\ntext-align: ;")
                  ("ovh,ta," "… text-align: ;" "overflow: hidden;\ntext-align: ;")
                  ("ovh,posa" "… position: absolute; z-index: ;"
                   "overflow: hidden;\nposition: absolute;\nz-index: ;")))
    (emmet2-test--with-css-completion (car case)
      (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions (car case) (nth 2 data))))
             (label (cadar (funcall (plist-get props :affixation-function) (list candidate)))))
        (should (equal label (nth 1 case)))
        (should-not (get-text-property 0 'face label))
        (should (get-text-property 2 'face label))
        (with-current-buffer (funcall (plist-get props :company-doc-buffer) candidate)
          (should (equal (buffer-substring-no-properties (point-min) (point-max)) (nth 2 case))))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (equal (buffer-string)
                       (concat ".a{" (string-replace "\n" "\n   " (nth 2 case)) "}")))))))

(ert-deftest emmet2-capf-current-fragment-honors-nested-and-quoted-commas ()
  (dolist (input '("p[calc(1px,2px)],ta" "ct['a,b'],ta"))
    (emmet2-test--with-css-completion input
      (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
             (candidate (car (all-completions input (nth 2 data)))))
        (should (equal (cadar (funcall (plist-get props :affixation-function) (list candidate)))
                       "… text-align: ;"))
        (funcall (plist-get props :exit-function) candidate 'finished)
        (should (string-match-p (if (string-prefix-p "p" input) "calc(1px,2px)" "'a,b'")
                                (buffer-string)))))))

(ert-deftest emmet2-capf-current-fragment-is-prepared-once-per-revision ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let ((expand (symbol-function 'emmet2--expand-analysis))
          (prepare (symbol-function 'emmet2-capf--preview-text))
          (display (symbol-function 'emmet2-capf--display))
          expanded (prepared 0) (displayed 0))
      (cl-letf (((symbol-function 'emmet2--expand-analysis)
                 (lambda (analysis)
                   (push (plist-get analysis :abbr) expanded) (funcall expand analysis)))
                ((symbol-function 'emmet2-capf--preview-text)
                 (lambda (&rest args) (cl-incf prepared) (apply prepare args)))
                ((symbol-function 'emmet2-capf--display)
                 (lambda (&rest args) (cl-incf displayed) (apply display args))))
        (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data))
               (candidates (all-completions "ovh,ta" table))
               (calls (length expanded)))
          (should (= (cl-count "ovh" expanded :test #'equal) 1))
          (should (= prepared (length candidates)))
          (should (= displayed (length candidates)))
          (dotimes (_ 3)
            (funcall (plist-get props :affixation-function) candidates)
            (dolist (candidate candidates) (funcall (plist-get props :company-doc-buffer) candidate)))
          (should (= calls (length expanded)))
          (should (= prepared (length candidates)))
          (should (= displayed (length candidates)))
          (insert "c")
          (should (= (length (all-completions "ovh,tac" table)) 1))
          (should (= (cl-count "ovh" expanded :test #'equal) 2))
          (should (= prepared (1+ (length candidates))))
          (should (= displayed (1+ (length candidates)))))))))

(ert-deftest emmet2-capf-affixation-validates-the-whole-batch ()
  (emmet2-test--with-css-completion "ovh,ta"
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ovh,ta" (nth 2 data)))
           (affix (plist-get props :affixation-function))
           (analyze (symbol-function 'emmet2-context-analyze)) (analyses 0))
      (should (> (length candidates) 1))
      (cl-letf (((symbol-function 'emmet2-context-analyze)
                 (lambda (&rest args) (cl-incf analyses) (apply analyze args))))
        (let ((rows (funcall affix candidates)))
          (should (= analyses 1))
          (should (equal (mapcar #'cadr rows)
                         (mapcar (lambda (candidate)
                                   (plist-get (get-text-property 0 'emmet2--choice candidate) :label))
                                 candidates)))
          (should (equal (mapcar #'car rows) candidates))))
      ;; Matching text from another table cannot borrow this table's result.
      (let ((foreign (car (all-completions "ovh,ta" (nth 2 (emmet2-capf))))))
        (should (equal (cadar (funcall affix (list foreign))) "")))
      ;; Display callbacks may not refresh an input revision after an edit.
      (insert "c")
      (should (cl-every (lambda (row) (equal (cadr row) "")) (funcall affix candidates)))
      (dolist (candidate candidates)
        (should-not (funcall (plist-get props :company-doc-buffer) candidate))
        (funcall (plist-get props :exit-function) candidate 'finished))
      (should (equal (buffer-string) ".a{ovh,tac}")))))

(ert-deftest emmet2-capf-current-fragment-preserves-css-in-js-insertion ()
  (with-temp-buffer
    (insert "const A=(<main style={{ovh,ta}} />);") (tsx-ts-mode)
    (goto-char (point-min)) (search-forward "ovh,ta")
    (emmet2-context--prepare)
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ovh,ta" (nth 2 data)))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (index (cl-position "… textAlign: \"right\"" (mapcar #'cadr rows) :test #'equal)))
      (should (numberp index))
      (should-not (funcall (plist-get props :company-doc-buffer) (nth index candidates)))
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) "const A=(<main style={{overflow: \"hidden\", textAlign: \"right\"}} />);")))))

(ert-deftest emmet2-capf-pending-comma-keeps-strict-syntax-boundaries ()
  (dolist (input '("m10,," "m10,+" "p[1," "p(calc(1px,"))
    (with-temp-buffer
      (css-mode) (insert ".a{" input "}") (backward-char)
      (when-let* ((data (emmet2-capf)))
        (should-not (all-completions input (nth 2 data))))))
  (with-temp-buffer
    (css-mode) (insert ".a{p[calc(1px,2px)],}") (backward-char)
    (let* ((data (emmet2-capf))
           (candidate (car (all-completions "p[calc(1px,2px)]," (nth 2 data)))))
      (funcall (plist-get (nthcdr 3 data) :exit-function) candidate 'finished)
      (should (equal (buffer-string) ".a{padding: calc(1px,2px);}")))))

(ert-deftest emmet2-capf-corfu-choices-through-styles-manual-and-tab ()
  (dolist (styles '((basic partial-completion) (partial-completion basic) (partial-completion)))
    (dolist (automatic '(nil t))
      (emmet2-test--with-css-completion "ta"
        (let ((completion-styles styles)
              (completion-in-region-function #'corfu--in-region-1)
              (completion-cycle-threshold nil))
          (if automatic (corfu-auto--complete-deferred)
            (emmet2-complete) (corfu--exhibit))
          (should (> corfu--total 1))
          (let* ((rows (cdr (corfu--affixate corfu--candidates)))
                 (index (cl-position "text-align: center;" (mapcar #'cadr rows) :test #'equal)))
            (should (> index 0))
            (corfu--goto index)
            (corfu-complete)
            (should (equal (buffer-string) ".a{text-align: center;}"))))))))

(ert-deftest emmet2-capf-corfu-middle-edit-keeps-session ()
  (emmet2-test--with-css-completion "m10"
    (backward-char)
    (corfu-auto--complete-deferred)
    (insert "2")
    (cl-letf (((symbol-function 'corfu--popup-hide)
               (lambda () (ert-fail "Editing inside the abbreviation must not hide the popup"))))
      (let ((this-command 'self-insert-command)) (corfu--post-command)))
    (should completion-in-region-mode)
    (corfu-insert)
    (should (equal (buffer-string) ".a{margin: 120px;}"))))

(ert-deftest emmet2-capf-old-choice-cannot-be-accepted-after-input-roundtrip ()
  (emmet2-test--with-css-completion "m10"
    (let* ((data (emmet2-capf)) (table (nth 2 data))
           (exit (plist-get (nthcdr 3 data) :exit-function))
           (old (car (all-completions "m10" table))))
      (insert "0") (should (all-completions "m100" table))
      (delete-char -1)
      (let ((current (car (all-completions "m10" table))))
        (funcall exit old 'finished)
        (should (equal (buffer-string) ".a{m10}"))
        (funcall exit current 'finished)
        (should (equal (buffer-string) ".a{margin: 10px;}"))))))

(ert-deftest emmet2-capf-css-in-js-alternative-keeps-host-formatting ()
  (with-temp-buffer
    (insert "const A=(<main style={{ta}} />);") (tsx-ts-mode)
    (search-backward "ta}}") (forward-char 2) (emmet2-mode 1)
    (emmet2-context-analyze)
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidates (all-completions "ta" (nth 2 data)))
           (rows (funcall (plist-get props :affixation-function) candidates))
           (index (cl-position "textAlign: \"right\"" (mapcar #'cadr rows) :test #'equal)))
      (should index)
      (funcall (plist-get props :exit-function) (nth index candidates) 'finished)
      (should (equal (buffer-string) "const A=(<main style={{textAlign: \"right\"}} />);")))))

(ert-deftest emmet2-capf-corfu-multiline-to-single-line-hides-info-only ()
  (emmet2-test--with-css-completion "m10+p20"
    (corfu-auto--complete-deferred)
    (should (string-match-p "margin: 10px;\n" (corfu-popupinfo--get-documentation (car corfu--candidates))))
    (delete-region (- (point) 4) (point))
    (let ((this-command 'delete-backward-char)) (corfu--post-command))
    (should completion-in-region-mode)
    (let ((corfu-popupinfo--candidate nil)
          (corfu-popupinfo--function #'corfu-popupinfo--get-documentation)
          hidden)
      (cl-letf (((symbol-function 'corfu-popupinfo--visible-p) (lambda (&optional _) t))
                ((symbol-function 'corfu-popupinfo--hide) (lambda () (setq hidden t))))
        (corfu-popupinfo--show (car corfu--candidates)))
      (should hidden)
      (should completion-in-region-mode))))

(ert-deftest emmet2-capf-single-line-is-not-truncated-or-documented ()
  (emmet2-test--with-capf (concat "p{" (make-string 140 ?x) "}")
    (let* ((data (emmet2-capf)) (props (nthcdr 3 data))
           (candidate (car (all-completions (buffer-string) (nth 2 data))))
           (row (car (funcall (plist-get props :affixation-function) (list candidate)))))
      (should (equal (cadr row) (concat "<p>" (make-string 140 ?x) "</p>")))
      (should-not (funcall (plist-get props :company-doc-buffer) candidate)))))

(ert-deftest emmet2-capf-choices-are-lazy-and-reused-per-revision ()
  (emmet2-test--with-css-completion "ta"
    (let ((expand (symbol-function 'emmet2--expand-analysis)) (calls 0))
      (cl-letf (((symbol-function 'emmet2--expand-analysis)
                 (lambda (analysis) (cl-incf calls) (funcall expand analysis))))
        (let* ((data (emmet2-capf)) (table (nth 2 data)) (props (nthcdr 3 data)))
          (completion-metadata "ta" table nil)
          (should (= calls 0))
          (let ((candidates (all-completions "ta" table)))
            (should (> (length candidates) 1))
            (let ((expanded calls))
              (funcall (plist-get props :affixation-function) candidates)
              (all-completions "ta" table)
              (dolist (candidate candidates)
                (funcall (plist-get props :company-doc-buffer) candidate))
              (should (= expanded calls)))))))))

(ert-deftest emmet2-capf-css-keywords-through-corfu ()
  (dolist (case '(("tac" 3 "text-align: center;")
                  ("dn" 2 "display: none;") ("dn" 3 nil)
                  ("posr" 3 "position: relative;")))
    (with-temp-buffer
      (css-mode) (insert ".a{" (car case) "}") (backward-char) (emmet2-mode 1)
      (let ((corfu-auto-prefix (nth 1 case)) (corfu-auto-trigger nil)
            (corfu-on-exact-match 'show) (corfu-preview-current nil)
            (completion-styles '(basic partial-completion))
            (completion-category-defaults nil) (completion-category-overrides nil)
            (last-command-event (aref (car case) (1- (length (car case))))) shown)
        (cl-letf (((symbol-function 'corfu--candidates-popup) (lambda (&rest _) (setq shown t)))
                  ((symbol-function 'corfu--popup-hide) #'ignore)
                  ((symbol-function 'corfu--protect) #'funcall))
          (unwind-protect
              (progn
                (corfu-auto--complete-deferred)
                (should (eq (not (null shown)) (not (null (nth 2 case)))))
                (when shown (corfu-insert))
                (should (equal (buffer-string) (concat ".a{" (or (nth 2 case) (car case)) "}"))))
            (when completion-in-region-mode (corfu-quit))))))))

(ert-deftest emmet2-capf-rejects-every-stale-source ()
  (dolist (change '(outside delete-restore point mode narrow disabled options indent host buffer))
    (ert-info ((format "%s" change))
      (emmet2-test--with-capf "<main>ul>li*2</main>"
        (goto-char 14)
        (let* ((data (emmet2-capf)) (table (nth 2 data))
               (exit (plist-get (nthcdr 3 data) :exit-function))
               (abbr "ul>li*2"))
          (should (equal (all-completions abbr table) (list abbr)))
          (pcase change
            ('outside (save-excursion (goto-char (point-min)) (insert "x")))
            ('delete-restore (delete-char -1) (insert "2"))
            ('point (backward-char))
            ('mode (text-mode))
            ('narrow (narrow-to-region 8 14))
            ('disabled (emmet2-mode -1))
            ('options (setq-local emmet2-markup-variant "solid"))
            ('indent (setq-local web-mode-markup-indent-offset 9))
            ('host
             (let ((tick (buffer-chars-modified-tick)))
               (setq-local web-mode-content-type "jsx")
               (should (= tick (buffer-chars-modified-tick))))))
          (cl-flet ((reject ()
                      (let ((before (buffer-string)) (position (point)))
                        (should-not (all-completions abbr table))
                        (funcall exit abbr 'finished)
                        (should (equal (buffer-string) before))
                        (should (= position (point))))))
            (if (eq change 'buffer)
                (with-temp-buffer (insert "<main>ul>li*2</main>") (web-mode) (goto-char 14) (reject))
              (reject))))))))

(ert-deftest emmet2-capf-exit-status-and-candidate-guard ()
  (dolist (status '(exact sole nil cancelled))
    (emmet2-test--with-capf "ul>li*3"
      (let ((exit (plist-get (nthcdr 3 (emmet2-capf)) :exit-function)))
        (funcall exit "ul>li*3" status)
        (funcall exit "div.card" 'finished)
        (should (equal (buffer-string) "ul>li*3"))))))

(ert-deftest emmet2-capf-backend-failure-and-source-change ()
  (dolist (failure '(parse quit backend source))
    (emmet2-test--with-capf "ul>li*3"
      (let ((attempts 0))
        (cl-letf (((symbol-function 'emmet2--expand-analysis)
                   (lambda (_)
                     (cl-incf attempts)
                     (pcase failure
                       ('parse (signal 'emmet2-parse-error '("invalid" 0)))
                       ('quit (signal 'quit nil))
                       ('backend (signal 'emmet2-backend-error '("Expansion deadline exceeded")))
                       ('source (insert "4") (emmet2-result-create "unsafe"))))))
          (if (eq failure 'quit)
              (should (eq (condition-case nil (all-completions "ul>li*3" table)
                            (quit 'cancelled)) 'cancelled))
            ;; A failed session never retries the expansion or signals to the frontend.
            (should-not (all-completions "ul>li*3" table))
            (should-not (all-completions "ul>li*3" table))
            (should (= attempts 1)))
          (should (equal (buffer-string) (if (eq failure 'source) "ul>li*34" "ul>li*3"))))))))

(ert-deftest emmet2-capf-mode-registration-and-command-isolation ()
  (let ((global completion-at-point-functions))
    (with-temp-buffer
      (insert "div") (web-mode)
      (let ((other (lambda () (error "Other capf must not run"))))
        (setq-local completion-at-point-functions (list other))
        (emmet2-mode 1) (emmet2-mode 1)
        (should (equal completion-at-point-functions (list #'emmet2-capf other)))
        (should-error (emmet2-complete) :type 'user-error)
        (should (equal completion-at-point-functions (list #'emmet2-capf other)))
        (emmet2-mode -1)
        (should (equal completion-at-point-functions (list other)))))
    (should (equal completion-at-point-functions global))))

(ert-deftest emmet2-capf-explicit-command-warms-but-keeps-host-gate ()
  (with-temp-buffer
    (insert "const A=(<main>ul>li*2</main>);") (tsx-ts-mode) (search-backward "</main>")
    (let ((completion-in-region-function (lambda (_beg _end table &optional _pred)
                                           (should (test-completion "ul>li*2" table)) t)))
      (should-not (emmet2-capf))
      (emmet2-complete)
      (should (emmet2-capf))))
  (with-temp-buffer
    (insert "const A=()=>ul>li*2;") (tsx-ts-mode) (backward-char)
    (should-error (emmet2-complete) :type 'user-error))
  (with-temp-buffer
    (insert "const A=(<main>ul>li*2</main>);") (tsx-ts-mode) (search-backward "</main>")
    (cl-letf (((symbol-function 'treesit-language-available-p) (lambda (&rest _) nil)))
      (should-not (emmet2-capf))
      (should-error (emmet2-complete) :type 'user-error))))

(ert-deftest emmet2-capf-corfu-acceptance-matrix-and-middle-point ()
  (dolist (configuration '(((basic partial-completion emacs22) nil)
                           ((partial-completion basic) nil)
                           ((partial-completion) nil)
                           ((basic partial-completion emacs22) ((emmet2 (styles partial-completion))))))
    (dolist (exact '(nil show insert quit))
      (dolist (command '(completion-at-point emmet2-complete))
        (dolist (middle '(nil t))
          (should (eq (cadr (emmet2-test--completion-session
                             (car configuration) (cadr configuration) exact nil nil nil t nil middle command))
                      'finished)))))))

(ert-deftest emmet2-capf-corfu-prompt-and-selection ()
  (dolist (select '(nil t))
    (let ((result
           (emmet2-test--completion-session
            '(basic partial-completion) nil nil nil nil nil nil 'prompt nil nil
            (lambda ()
              (should (= corfu--index -1))
              (when select (corfu-next))
              (corfu-insert)
              (should (equal (buffer-string)
                             (if select "<ul>\n    <li></li>\n    <li></li>\n    <li></li>\n</ul>" "ul>li*3")))))))
      (should (eq (cadr result) (and select 'finished))))))

(ert-deftest emmet2-capf-corfu-typing-refreshes-without-hiding ()
  (dolist (action '(insert delete))
    (save-window-excursion
      (let ((result
             (emmet2-test--completion-session
              '(basic partial-completion) nil nil nil "m1" nil nil nil nil nil
              (lambda ()
                (set-window-buffer (selected-window) (current-buffer))
                (let* ((old-table (nth 2 completion-in-region--data))
                       (old-candidate (car corfu--candidates))
                       (exit (plist-get (nth 4 completion-in-region--data) :exit-function)))
                  (if (eq action 'insert) (insert "4") (delete-char -1))
                  (let ((before (buffer-string)))
                    (cl-letf (((symbol-function 'corfu--popup-hide)
                               (lambda () (ert-fail "Typing must not hide the popup"))))
                      (let ((this-command (if (eq action 'insert) 'self-insert-command 'delete-backward-char)))
                        (corfu--post-command)))
                    (should completion-in-region-mode)
                    (should (eq (nth 2 completion-in-region--data) old-table))
                    (funcall exit old-candidate 'finished)
                    (should (equal (buffer-string) before))
                    (should (equal (substring-no-properties (car corfu--candidates))
                                   (if (eq action 'insert) "m14" "m")))))))))
        (should-not (cadr result))))))

(ert-deftest emmet2-capf-corfu-movement-outside-ends-session ()
  (save-window-excursion
    (emmet2-test--completion-session
     '(basic partial-completion) nil nil nil nil nil nil nil nil nil
     (lambda ()
       (set-window-buffer (selected-window) (current-buffer))
       (goto-char (point-min))
       (let ((this-command 'beginning-of-buffer)) (corfu--post-command))
       (should-not completion-in-region-mode)))))

(ert-deftest emmet2-capf-corfu-buffer-switch-and-killed-source ()
  (should-not
   (cadr
    (emmet2-test--completion-session
     '(basic partial-completion) nil nil nil nil nil nil nil nil nil
     (lambda ()
       (let ((source (current-buffer)))
         (with-temp-buffer
           (insert "other buffer")
           ;; Corfu's post-command observer sees the actual buffer change.
           (corfu--post-command)
           (should-not completion-in-region-mode)
           (should (equal (buffer-string) "other buffer")))
         (should (equal (with-current-buffer source (buffer-string)) "ul>li*3")))))))
  (let (captured-table exit)
    (emmet2-test--with-capf "ul>li*3"
      (let ((data (emmet2-capf)))
        (setq captured-table (nth 2 data) exit (plist-get (nthcdr 3 data) :exit-function))))
    (should (functionp captured-table))
    (with-temp-buffer
      (insert "ul>li*3")
      (should-not (all-completions "ul>li*3" captured-table))
      (funcall exit "ul>li*3" 'finished)
      (should (equal (buffer-string) "ul>li*3")))))

(ert-deftest emmet2-capf-auto-threshold-does-not-expand ()
  (with-temp-buffer
    (insert ".a{m1}") (css-mode) (backward-char) (emmet2-mode 1)
    (let ((corfu-auto-prefix 3) (corfu-auto-trigger nil) (last-command-event ?1))
      (cl-letf (((symbol-function 'emmet2--expand-analysis)
                 (lambda (_) (ert-fail "Below-threshold candidate must stay lazy")))
                ((symbol-function 'corfu--protect) #'funcall))
        (corfu-auto--complete-deferred)
        (should-not completion-in-region-mode)
        (should (equal (buffer-string) ".a{m1}"))))))

(ert-deftest emmet2-capf-frontend-free-acceptance-and-undo ()
  (emmet2-test--with-capf "ul>li*3"
    (buffer-enable-undo)
    (let ((completion-styles '(partial-completion))
          (completion-category-defaults nil) (completion-category-overrides nil)
          (completion-in-region-function #'completion--in-region)
          (completion-cycle-threshold nil))
      (completion-at-point)
      (should (string-prefix-p "<ul>" (buffer-string)))
      (undo 1)
      (should (equal (buffer-string) "ul>li*3")))))

(ert-deftest emmet2-capf-read-only-and-invalid-syntax ()
  (emmet2-test--with-capf "ul>li*3"
    (setq buffer-read-only t)
    (should-not (emmet2-capf)))
  (with-temp-buffer
    (insert ".a{p(1}") (css-mode) (backward-char)
    (let ((table (nth 2 (emmet2-capf))))
      (should table)
      (should-not (all-completions "p(1" table)))))

(provide 'emmet2-capf-test)
;;; emmet2-capf-test.el ends here
