;;; emmet2-corfu-test.el --- Optional Corfu display contracts -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'emmet2-capf-test)
(require 'emmet2-corfu)
(require 'emmet2-completion)

(ert-deftest emmet2-corfu-short-labels-preserve-properties-and-isolation ()
  (let ((corfu--metadata '(metadata (category . emmet2)))
        (completion-in-region--data '(nil nil nil nil nil))
        (corfu-max-width 20))
    (dolist (value '("margin: 0;" "界😀" ""))
      (let* ((label (propertize value 'face 'completions-common-part))
             (rows (list (list "abbr" label "")))
             (text (caar (car (emmet2-corfu--rows (list rows))))))
        (should (equal-including-properties label text))
        (when (> (length text) 0)
          (put-text-property 0 1 'face 'error text)
          (should (eq (get-text-property 0 'face label) 'completions-common-part)))))))

(ert-deftest emmet2-corfu-label-column-preserves-choice-and-undo ()
  (emmet2-test--with-css-completion "ta"
    (let ((corfu-max-width 12) shown)
      (cl-letf (((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (= (nth 1 shown) 0))
        (should (<= (nth 2 shown) 12))
        (dolist (line (nth 3 shown))
          (should (<= (string-width line) 12)))
        (should (seq-some (lambda (line) (string-suffix-p "…" line)) (nth 3 shown)))
        (let* ((candidates (copy-sequence corfu--candidates))
               (rows (cdr (corfu--affixate candidates)))
               (index (cl-position "text-align: center;" (mapcar #'cadr rows) :test #'equal)))
          (should (numberp index))
          (corfu--goto index)
          (corfu--exhibit)
          (should (equal-including-properties candidates corfu--candidates))
          (should (cl-every (lambda (candidate) (equal candidate "ta")) candidates))
          (corfu-insert)
          (should (equal (buffer-string) ".a{text-align: center;}"))
          (undo-only 1)
          (should (equal (buffer-string) ".a{ta}")))))))

(ert-deftest emmet2-corfu-rows-stay-plain-text-with-margin-formatters ()
  (emmet2-test--with-css-completion "ta"
    (let ((corfu-max-width 40)
          (corfu-margin-formatters (list (lambda (_metadata) (lambda (_candidate) "[I] "))))
          shown)
      (cl-letf (((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (= (nth 1 shown) 0))
        (should (member "text-align: center;" (mapcar #'substring-no-properties (nth 3 shown))))
        (should-not (seq-some (lambda (line) (string-search "[I]" line)) (nth 3 shown)))))))

(ert-deftest emmet2-corfu-anchor-refresh-and-new-session ()
  (emmet2-test--with-css-completion "ta"
    (let ((start (point)) shown)
      (cl-letf (((symbol-function 'posn-at-point)
                 (lambda (&optional position _window) (list (or position (point)))))
                ((symbol-function 'corfu--popup-show)
                 (lambda (&rest arguments) (setq shown arguments))))
        (corfu-auto--complete-deferred)
        (should (equal (car shown) (list start)))
        (insert "c")
        (let ((this-command 'self-insert-command)) (corfu--post-command))
        (should completion-in-region-mode)
        (should (equal (car shown) (list start)))
        (corfu-quit)
        (corfu-auto--complete-deferred)
        (should (equal (car shown) (list (1+ start))))))))

(ert-deftest emmet2-corfu-display-honors-frame-width-and-unicode ()
  (let* ((label (propertize "界😀long-label" 'face 'completions-common-part))
         (candidate (propertize "abbr" 'emmet2--choice 'identity))
         (rows (list (list candidate label "")))
         (corfu--metadata '(metadata (category . emmet2)))
         (completion-in-region--data '(nil nil nil nil nil))
         (corfu-max-width 100))
    (cl-letf (((symbol-function 'frame-width) (lambda (&optional _) 10)))
      (let ((text (caar (car (emmet2-corfu--rows (list rows))))))
        (should (<= (string-width text) 6))
        (should (string-suffix-p "…" text))
        (should (eq (get-text-property 0 'face text) 'completions-common-part))
        (should (eq (get-text-property 0 'emmet2--choice candidate) 'identity))
        (should (equal label "界😀long-label"))))))

(ert-deftest emmet2-corfu-other-categories-pass-through ()
  (let* ((arguments (list '(("name" "prefix" "suffix"))))
         (corfu--metadata '(metadata (category . eglot)))
         (completion-in-region--data '(nil nil nil nil (:other-property t)))
         (properties (nth 4 completion-in-region--data)))
    (should (eq (emmet2-corfu--rows arguments) arguments))
    (cl-letf (((symbol-function 'posn-at-point)
               (lambda (&rest _) (ert-fail "Foreign completion must keep its position"))))
      (should (eq (emmet2-corfu--anchor #'identity 'original-position) 'original-position)))
    (should (eq (nth 4 completion-in-region--data) properties))
    (should-not (plist-member properties :emmet2-corfu-anchor))
    ;; A foreign sole exact match keeps the user's `corfu-on-exact-match' policy.
    (emmet2-corfu--enable)
    (should (eq (corfu--try-completion "foo" '("foo") nil 3) t))))

(defun emmet2-corfu-test--replacements (unguarded function)
  "Return FUNCTION's value and the number of line-break replacements it ran.
Only Corfu's replacements that reach the replacement function count.
Non-nil UNGUARDED runs FUNCTION as if no table were emmet2's."
  (let* ((calls 0)
         (count (lambda (regexp &rest _)
                  (when (equal regexp "[ \t]*\n[ \t]*") (cl-incf calls)))))
    (advice-add 'replace-regexp-in-string :before count)
    (unwind-protect
        (cl-letf (((symbol-function 'emmet2-corfu--own-table-p)
                   (if unguarded #'ignore (symbol-function 'emmet2-corfu--own-table-p))))
          (list (funcall function) calls))
      (advice-remove 'replace-regexp-in-string count))))

(defun emmet2-corfu-test--format (metadata rows &optional unguarded)
  "Return (RESULT CALLS) after Corfu formats ROWS of a METADATA table in place.
CALLS and UNGUARDED are as in `emmet2-corfu-test--replacements'."
  (let ((corfu--metadata metadata) (corfu--width 0) (corfu-min-width 15) (corfu-max-width 100)
        (completion-in-region--data '(nil nil nil nil nil)))
    (emmet2-corfu-test--replacements unguarded (lambda () (corfu--format-candidates rows)))))

(defun emmet2-corfu-test--rows ()
  "Return fresh rows with and without line breaks, as a frontend affixes them."
  (list (list (propertize "red" 'face 'completions-common-part) ""
              (propertize "  color" 'face 'corfu-annotations))
        (list (propertize "wide\n  label" 'face 'bold) "" (propertize " a\tb\n" 'face 'italic))
        (list "" "" "")))

(ert-deftest emmet2-corfu-own-rows-skip-copies-and-keep-output ()
  (emmet2-corfu--enable)
  (dolist (metadata '((metadata (category . scss2) (emmet2-identity . identity))
                      (metadata (category . emmet2-value) (emmet2-identity . identity))))
    (let* ((rows (emmet2-corfu-test--rows))
           (strings (copy-sequence (car rows))))
      (pcase-let ((`(,result ,calls) (emmet2-corfu-test--format metadata rows))
                  (`(,expected ,all) (emmet2-corfu-test--format
                                      metadata (emmet2-corfu-test--rows) t)))
        (should (= all 9))
        ;; Only the strings with a line break reach the replacement.
        (should (= calls 2))
        (should (eq (car (nth 0 rows)) (car strings)))
        (should (eq (nth 2 (nth 0 rows)) (nth 2 strings)))
        (should (equal (car (nth 1 rows)) "wide label"))
        (should (equal-including-properties result expected)))))
  (let ((metadata '(metadata (category . emmet2)))
        (rows (list (list (propertize "ta" 'emmet2--label (propertize "text-align: center;" 'face 'bold))
                          "" "  annotation"))))
    (pcase-let ((`(,result ,calls) (emmet2-corfu-test--format metadata rows))
                (`(,expected ,all) (emmet2-corfu-test--format metadata rows t)))
      (should (= all 3))
      (should (= calls 0))
      (should (equal-including-properties result expected)))))

(ert-deftest emmet2-corfu-guard-leaves-other-replacements-and-tables ()
  (emmet2-corfu--enable)
  (let* ((seen nil)
         (probe (lambda (&rest _)
                  (push (list (replace-regexp-in-string "o" "0" "foo")
                              (replace-regexp-in-string "[ \t]*\n[ \t]*" "-" "a b")
                              (replace-regexp-in-string "[ \t]*\n[ \t]*" " " "ab" nil nil nil 1))
                        seen))))
    (advice-add 'corfu--format-candidates :before probe '((depth . 100)))
    (unwind-protect
        (pcase-let ((`(,_ ,calls) (emmet2-corfu-test--format
                                   '(metadata (category . scss2) (emmet2-identity . identity))
                                   (emmet2-corfu-test--rows))))
          ;; Two row strings with line breaks, then the probe's own two calls.
          (should (= calls 4))
          (should (equal (car seen) '("f00" "a b" "b"))))
      (advice-remove 'corfu--format-candidates probe)))
  ;; Foreign tables keep every copy; once Corfu skips them itself, remove the INTERIM guard.
  (dolist (metadata '((metadata (category . eglot)) (metadata)))
    (let* ((rows (emmet2-corfu-test--rows))
           (strings (copy-sequence (car rows))))
      (pcase-let ((`(,_ ,calls) (emmet2-corfu-test--format metadata rows)))
        (should (= calls 9))
        (should-not (eq (car (nth 0 rows)) (car strings)))))))

(ert-deftest emmet2-corfu-popup-rows-are-unchanged-by-the-guard ()
  ;; An Emmet table and a value table built by `emmet2-completion-capf'.
  (dolist (input '("ta" "color: r"))
    (let (results)
      (dolist (unguarded '(nil t))
        (emmet2-test--with-css-completion input
          (let ((corfu-max-width 40) shown)
            (cl-letf (((symbol-function 'corfu--popup-show)
                       (lambda (&rest arguments) (setq shown arguments))))
              (pcase-let ((`(,_ ,calls) (emmet2-corfu-test--replacements
                                         unguarded #'corfu-auto--complete-deferred)))
                (push (list (nth 3 shown) calls) results))))))
      (pcase-let ((`((,plain ,all) (,rows ,calls)) results))
        (should (> (length rows) 1))
        (should (> all 0))
        (should (= calls 0))
        (should (equal-including-properties rows plain))))))

(ert-deftest emmet2-corfu-emmet-input-is-never-complete ()
  ;; Text after point makes even `basic' report the sole choice as exact.
  (with-temp-buffer
    (insert "<main>a[href=\"\"]</main>") (web-mode) (emmet2-mode 1)
    (search-backward "\"]")
    (pcase-let ((`(,beg ,end ,table) (emmet2-capf)))
      (let ((str (buffer-substring-no-properties beg end)) (pt (- (point) beg)))
        (should (eq (completion-try-completion str table nil pt) t))
        (should (equal (corfu--try-completion str table nil pt) (cons str pt)))))))

(ert-deftest emmet2-corfu-installation-and-unload ()
  (let ((compiled (byte-code-function-p (symbol-function 'emmet2-corfu--rows))))
    (unwind-protect
        (progn
          (dotimes (_ 3) (emmet2-corfu--enable))
          (dolist (entry '((corfu--format-candidates . emmet2-corfu--rows)
                           (corfu--format-candidates . emmet2-corfu--format)
                           (corfu--candidates-popup . emmet2-corfu--anchor)
                           (corfu--try-completion . emmet2-corfu--try-completion)))
            (let ((count 0))
              (advice-mapc (lambda (function _properties)
                             (when (eq function (cdr entry)) (cl-incf count))) (car entry))
              (should (= count 1))))
          ;; Advice added afterwards keeps its position on later enables.
          (let ((outer (lambda (arguments) arguments)))
            (advice-add 'corfu--format-candidates :filter-args outer)
            (emmet2-corfu--enable)
            (let (order)
              (advice-mapc (lambda (function _properties) (push function order))
                           'corfu--format-candidates)
              (should (eq (car (last order)) outer)))
            (advice-remove 'corfu--format-candidates outer))
          (emmet2-mode-unload-function)
          (should-not (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (should-not (advice-member-p #'emmet2-corfu--format 'corfu--format-candidates))
          (should-not (advice-member-p #'emmet2-corfu--anchor 'corfu--candidates-popup))
          (should-not (advice-member-p #'emmet2-corfu--try-completion 'corfu--try-completion))
          ;; Semantic tables install the adapter only for the interim line-break guard.
          (with-temp-buffer
            (insert "r")
            (should (emmet2-completion-capf 1 2 '(("red")))))
          (should (advice-member-p #'emmet2-corfu--format 'corfu--format-candidates))
          (should (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (emmet2-corfu-unload-function)
          (should-not (advice-member-p #'emmet2-corfu--format 'corfu--format-candidates))
          ;; Independent hosts may keep using CAPF after the minor mode unloads.
          (with-temp-buffer
            (css-mode) (insert ".a{ta}") (backward-char)
            (should (emmet2-capf)))
          (should (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (unload-feature 'emmet2-corfu t)
          (should-not (advice-member-p 'emmet2-corfu--rows 'corfu--format-candidates))
          (should-not (advice-member-p 'emmet2-corfu--format 'corfu--format-candidates))
          (should-not (advice-member-p 'emmet2-corfu--anchor 'corfu--candidates-popup))
          (should-not (advice-member-p 'emmet2-corfu--try-completion 'corfu--try-completion))
          (with-temp-buffer
            (css-mode) (insert ".a{ta}") (backward-char)
            (should (emmet2-capf)))
          (should (advice-member-p #'emmet2-corfu--rows 'corfu--format-candidates))
          (should (advice-member-p #'emmet2-corfu--format 'corfu--format-candidates))
          (should (eq compiled (byte-code-function-p (symbol-function 'emmet2-corfu--rows)))))
      (require 'emmet2-corfu)
      (emmet2-corfu--enable))))

(provide 'emmet2-corfu-test)
;;; emmet2-corfu-test.el ends here
