;;; emmet2-extensions-css-test.el --- CSS expansion contracts -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'emmet2-extensions)

;; These are copied baseline assertions, not results generated by the new engine.
;; Each former ordinal has its own durable ERT identity, including duplicate names.
(dolist (entry (with-temp-buffer
                 (insert-file-contents (expand-file-name "test/fixtures/css-legacy.json" emmet2-test-root))
                 (json-parse-buffer :object-type 'alist :array-type 'list :false-object nil)))
  (let ((input (alist-get 'abbreviation entry)) (expected (alist-get 'text entry))
        (css-in-js (alist-get 'cssInJs entry)))
    (eval `(ert-deftest ,(intern (concat "emmet2-css-legacy-" (alist-get 'id entry))) ()
             (should (equal (plist-get (emmet2-extensions-css ,input :css-in-js ,css-in-js) :text)
                            ,expected))) t)))

(ert-deftest emmet2-css-independent-fields-and-collapse ()
  (should (equal (emmet2-extensions-css "bd")
                 '(:text "border: ;" :fields ((8 8 1 "")) :cursor 8)))
  (should (equal (emmet2-extensions-css "c+bg")
                 '(:text "color: ;\nbackground: ;" :fields ((7 7 1 "") (21 21 2 "")) :cursor 7)))
  (should (equal (emmet2-extensions-css "m+p")
                 '(:text "margin: ;\npadding: ;" :fields ((8 8 1 "") (19 19 2 "")) :cursor 8)))
  (should (equal (emmet2-extensions-css "all")
                 '(:text "top: ;\nright: ;\nbottom: ;\nleft: ;"
                         :fields ((5 5 1 "") (14 14 2 "") (24 24 3 "") (32 32 4 "")) :cursor 5)))
  (dolist (abbr '("bd[solid]" "gtc[1fr 1fr]" "c--primary" "m(2)"))
    (should-not (plist-get (emmet2-extensions-css abbr) :fields))))

(ert-deftest emmet2-css-collapse-includes-right-boundary-field ()
  (let* ((source (emmet2-result-create "x: a b;" '((3 4 1 "a") (5 6 2 "b") (6 6 3 ""))))
         (before (copy-tree source)))
    (should (equal (emmet2-extensions--clear-defaults source)
                   '(:text "x: ;" :fields ((3 3 1 "")) :cursor 3)))
    (should (equal source before)))
  (should (equal (emmet2-extensions--clear-defaults
                  (emmet2-result-create "x: a;" '((3 4 1 "a") (3 3 2 ""))))
                 '(:text "x: ;" :fields ((3 3 1 "")) :cursor 3))))

(ert-deftest emmet2-css-nested-and-quoted-separators ()
  (should (equal (emmet2-extensions--split "p[calc(1px + 2px), var(--x, 0)]+c" '(?+ ?,))
                 '("p[calc(1px + 2px), var(--x, 0)]" "c")))
  (should (equal (emmet2-extensions-css "p[calc(1px + 2px), var(--x, 0)]!+c")
                 '(:text "padding: calc(1px + 2px), var(--x, 0) !important;\ncolor: ;"
                         :fields ((57 57 1 "")) :cursor 57)))
  (should (equal (plist-get (emmet2-extensions-css "ct['😀,+\\\\path']+m0") :text)
                 "content: '😀,+\\\\path';\nmargin: 0;"))
  (dolist (input '("p[1" "p[1)" "p['a]" "p++m"))
    (should-error (emmet2-extensions-css input) :type 'emmet2-parse-error)))

(ert-deftest emmet2-css-js-escapes-and-fields ()
  (should (equal (emmet2-extensions-css "c+gtc" :css-in-js t)
                 '(:text "color: , gridTemplateColumns: \"repeat()\""
                         :fields ((7 7 1 "") (38 38 2 "")) :cursor 7)))
  (should (equal (emmet2-extensions-css "ct[\"😀\\path\"]+m" :css-in-js t)
                 '(:text "content: \"\\\"😀\\\\path\\\"\", margin: "
                         :fields ((32 32 1 "")) :cursor 32)))
  (let* ((source (emmet2-result-create "x\"\\\n😀" '((0 4 1 "x\"\\\n") (5 5 2 ""))))
         (before (copy-tree source)))
    (should (equal (emmet2-extensions--map-chars source #'emmet2-extensions--escape-js)
                   '(:text "x\\\"\\\\\\n😀" :fields ((0 7 1 "x\\\"\\\\\\n") (8 8 2 "")) :cursor 0)))
    (should (equal source before)))
  (dolist (pair '(("12px 12px" . "\"12px 12px\"") ("12px !important" . "\"12px !important\"")
                   ("center" . "\"center\"") ("0" . "0") ("0.5" . "0.5")
                   ("-100" . "-100") ("12px" . "12")))
    (should (equal (plist-get (emmet2-extensions-css (concat "p[" (car pair) "]") :css-in-js t) :text)
                   (concat "padding: " (cdr pair)))))
  (should (equal (plist-get (emmet2-extensions--js-property (emmet2-result-create "--a-b: x;")) :text)
                 "\"--a-b\": \"x\"")))

(ert-deftest emmet2-css-pseudo-functions-aliases-and-fallback ()
  (dolist (pair '((":h(+p)" . "&:has(+ p)") (":dis" . "&:disabled")
                   (":fo" . "&:first-of-type") ("_:fo" . ":first-of-type") (".c:fo" . ".c:first-of-type")
                   (".c:f-l" . ".c::first-letter")
                   ("a.c1.c2#id:fo" . "a.c1.c2#id:first-of-type")
                   (":n(:f-c)" . "&:not(:first-child)") ("a.c1.c2#id:f-c" . "a.c1.c2#id:first-child")
                   (":n(:f-c,:l-c)" . "&:not(:first-child):not(:last-child)")
                   (":n-c(2n-1)" . "&:nth-child(2n-1)") (":hov:af" . "&:hover::after")
                   (":n(:l-c):af" . "&:not(:last-child)::after")
                   (":be" . "&::before") ("_:fc:be" . ":first-child::before")
                   (":n(.a,.b):be" . "&:not(.a):not(.b)::before")
                   (":is(:h(+p),:fu)" . "&:is(:has(+ p)):is(:focus)")
                   (":popov" . "&:popover-open")))
    (ert-info ((car pair))
      (let* ((text (concat (cdr pair) " {\n\t\n}")) (cursor (- (length text) 2)))
        (should (equal (emmet2-extensions-css (car pair))
                       (list :text text :fields (list (list cursor cursor 1 "")) :cursor cursor))))))
  (should (equal (plist-get (emmet2-extensions-css "@i+") :text) "@i+"))
  (should (equal (plist-get (emmet2-extensions-css "@scop") :text) "@scope "))
  (should (equal (emmet2-extensions-css "@us")
                 '(:text "@use \"\";" :fields ((6 6 1 "")) :cursor 6))))

(ert-deftest emmet2-css-layout-does-not-rewrite-literal-tabs ()
  (should (equal (emmet2-extensions-css "m+p" :base-indent "  ")
                 '(:text "margin: ;\n  padding: ;" :fields ((8 8 1 "") (21 21 2 "")) :cursor 8)))
  (should (equal (emmet2-extensions-css ":fu" :indent "  " :base-indent "    ")
                 '(:text "&:focus {\n      \n    }" :fields ((16 16 1 "")) :cursor 16)))
  (should (equal (plist-get (emmet2-extensions-css "p[a\tb]" :indent "  ") :text) "padding: a\tb;"))
  (should (equal (emmet2-extensions-css "@else" :indent "  " :base-indent "    ")
                 '(:text "@else {\n      \n    }" :fields ((14 14 1 "")) :cursor 14))))

(ert-deftest emmet2-css-whole-expansion-shares-deadline ()
  (let ((now 0.0) (emmet2-engine--timeout 1.0) deadlines)
    (cl-letf (((symbol-function 'float-time) (lambda (&rest _) now))
              ((symbol-function 'emmet2-engine-expand)
               (lambda (&rest _)
                 (push emmet2-engine--deadline deadlines)
                 (cl-incf now 0.6)
                 (emmet2-result-create "top: ;" '((5 5 1 ""))))))
      (should-error (emmet2-extensions-css "t+r+b") :type 'emmet2-backend-error)
      (should (equal deadlines '(1.0 1.0))))))

(ert-deftest emmet2-css-opinionated-regression-inputs ()
  (dolist (pair '(("!" . "!important") ("p$a$b$c!" . "padding: $a $b $c !important;")
                   ("p(1)(2)(3)!" . "padding: rhythm(1) rhythm(2) rhythm(3) !important;")
                   ("all--gutter!" . "top: var(--gutter) !important;\nright: var(--gutter) !important;\nbottom: var(--gutter) !important;\nleft: var(--gutter) !important;")
                   ("p--a--b--c!" . "padding: var(--a) var(--b) var(--c) !important;")
                   ("p[var(--a) var(--b) var(--c)]!" . "padding: var(--a) var(--b) var(--c) !important;")
                   ("p!" . "padding: !important;") ("p--p" . "padding: var(--p);")
                   ("p[0 2px]" . "padding: 0 2px;")))
    (ert-info ((car pair))
      (should (equal (plist-get (emmet2-extensions-css (car pair)) :text) (cdr pair))))))

(ert-deftest emmet2-css-raw-and-nested-selector-regressions ()
  ;; Raw values belong to the extension layer; the core rejects the first input.
  ;; Pinned Emmet resolves `tn' to top; transition's abbreviation is `trs'.
  (should (equal (emmet2-extensions-css "tn[all 0.3s]")
                 '(:text "top: all 0.3s;" :fields nil :cursor 14)))
  (should (equal (emmet2-extensions-css "trs[all 0.3s]")
                 '(:text "transition: all 0.3s;" :fields nil :cursor 21)))
  (should (equal (emmet2-extensions-css "ff[Arial,sans-serif]")
                 '(:text "font-family: Arial,sans-serif;" :fields nil :cursor 30)))
  (should (equal (emmet2-extensions-css ":hv:n(:fc)")
                 '(:text "&:hover:not(:first-child) {\n\t\n}"
                         :fields ((29 29 1 "")) :cursor 29))))

(ert-deftest emmet2-css-alias-precedence-and-empty-alias-fallback ()
  (should (equal (emmet2-extensions-css ":fu")
                 '(:text "&:focus {\n\t\n}" :fields ((11 11 1 "")) :cursor 11)))
  (should (equal (emmet2-extensions-css "@fa")
                 '(:text "@font-face " :fields nil :cursor 11)))
  ;; Replace only the alias maps in a private copy.  Names, functions and
  ;; templates remain available, and the packaged overrides stay untouched.
  (let ((emmet2-extensions--overrides (copy-hash-table emmet2-extensions--overrides)))
    (dolist (key '("pseudoAliases" "atRuleAliases"))
      (puthash key (make-hash-table :test #'equal) emmet2-extensions--overrides))
    (should (equal (emmet2-extensions-css ":fu")
                   '(:text "&:future {\n\t\n}" :fields ((12 12 1 "")) :cursor 12)))
    (should (equal (emmet2-extensions-css "@fa")
                   '(:text "@forward \"\";" :fields ((10 10 1 "")) :cursor 10))))
  (should (equal (gethash ":fu" (gethash "pseudoAliases" emmet2-extensions--overrides)) ":focus"))
  (should (equal (gethash "@fa" (gethash "atRuleAliases" emmet2-extensions--overrides)) "@font-face")))

(ert-deftest emmet2-css-coalescing-preserves-distant-mirrors ()
  (let ((source (emmet2-result-create "x: a b/cb;"
                 '((3 4 1 "a") (5 6 2 "b") (7 8 3 "c") (8 9 2 "b")))))
    (should (equal (emmet2-extensions--clear-defaults source)
                   '(:text "x: /;" :fields ((3 3 1 "") (4 4 1 "")) :cursor 3)))))

(provide 'emmet2-extensions-css-test)
;;; emmet2-extensions-css-test.el ends here
