;;; emmet2-host-contract-test.el --- Host feasibility contracts -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'treesit)
(require 'web-mode)
(require 'emmet2-extract)

(require 'emmet2-context)

;; The original S0 real-point matrix now exercises the production context owner.
(defconst emmet2-test-host-cases
  '((tight "const A = () => (<main>ul>li*3│</main>);" markup "ul>li*3")
    (middle "const A = () => (<main>ul>│li*3</main>);" markup "ul>li*3")
    (text "const A = () => (<main>div{hello│ world}</main>);" markup "div{hello world}" manual)
    (text-punctuation "const A = () => (<main>p{don't│ [stop}</main>);" markup "p{don't [stop}" manual)
    (text-colon "const A=(<main>p{color:m10+p.5│}</main>);" markup "p{color:m10+p.5}" manual)
    (text-ambiguity "const A = () => (<main>Hello{items.ma│}</main>);" nil nil)
    (text-ambiguity-end "const A = () => (<main>Hello{items.ma}│</main>);" nil nil)
    (expression-after-point "const A = () => (<main>ul>li│{x}</main>);" nil nil)
    (text-explicit "const A = () => (<main>p{hello│}</main>);" markup "p{hello}" manual)
    (numbered-text "const A=(<main>ul>li.item$*5>a{Link $}│</main>);" markup "ul>li.item$*5>a{Link $}")
    (numbered-text-middle "const A=(<main>ul>li.item$*5>a{Link │$}</main>);" markup "ul>li.item$*5>a{Link $}")
    (numbered-text-explicit "const A=(<main>ul>li.item$*5>a{Link $}│</main>);" markup "ul>li.item$*5>a{Link $}" manual)
    (recovered-text-ambiguous "const A=(<main>Hello{Link $}│</main>);" nil nil)
    (recovered-text-explicit "const A=(<main>p{Link $}│</main>);" markup "p{Link $}" manual)
    (return-object-adjacent "function f(){return{m10│};}" nil nil manual)
    (arrow-object-adjacent "const f=()=>({m10│});" nil nil manual)
    (ordinary-expression-recovery "const x=foo{m10│};" nil nil manual)
    (expression "const A = () => (<main>{items.ma│}</main>);" nil nil)
    (expression-before-close "const A = () => (<main>{items.ma}│</main>);" nil nil)
    (attribute "const A = () => (<main title='ul>li│'/>);" nil nil)
    (style "const A = () => (<main style={{m1,p│2}}/>);" css-in-js "m1,p2")
    (raw "const A = () => (<main style={{p[1px│ 2px]}}/>);" css-in-js "p[1px 2px]")
    (other-attribute "const A = () => (<main other={{m10│}}/>);" nil nil)
    (computed-style "const A = () => (<main style={compute({m10│})}/>);" nil nil)
    (nested-computation "const s = createTheme({x: compute({m10│})});" nil nil)
    (style-value "const A = () => (<main style={{color: m10│}}/>);" nil nil)
    (malformed-style "const A = () => (<main style={{m10│/>);" nil nil)
    (stylesheet "const s = StyleSheet.create({x: {m1│0}});" css-in-js "m10")
    (theme "const s = createTheme({x: {p1│0}});" css-in-js "p10")
    (stylesheet-float "const s=StyleSheet.create({card:{m10+p.5│}});" css-in-js "m10+p.5")
    (theme-float "const s=createTheme({card:{m10+│p.5}});" css-in-js "m10+p.5")
    (style-float "const A=(<main style={{m10+p.5│}}/>);" css-in-js "m10+p.5")
    (ordinary-float "const s=ordinary({card:{m10+p.5│}});" nil nil)
    (object-float "const s={card:{m10+p.5│}};" nil nil)
    (computed-float "const s=createTheme({card:compute({m10+p.5│})});" nil nil)
    (style-value-float "const A=(<main style={{color:m10+p.5│}}/>);" nil nil)
    (style-other-float "const A=(<main other={{m10+p.5│}}/>);" nil nil)
    (style-closed-before-float "const s=StyleSheet.create({card:{m10}+p.5│});" nil nil)
    (style-unclosed-float "const s=StyleSheet.create({card:{m10+p.5│});" nil nil)
    (ordinary-call "const s = makeStyles({x: {m10│}});" nil nil)
    (ordinary-object "const s = {x: {m10│}};" nil nil)
    (string "const s = 'ul>li│';" nil nil)
    (comment "// ul>li│" nil nil)
    (root-auto "function A() { return ul>li│; }" nil nil)
    (root-manual "function A() { return ul>li│; }" markup "ul>li" manual)
    (map-auto "const A = items.map(x => ul>li│);" nil nil)
    (map-manual "const A = items.map(x => ul>li│);" markup "ul>li" manual)))

(ert-deftest emmet2-contract-host-jsx-real-point ()
  (dolist (configuration '((tsx-ts-mode . "tsx") (web-mode . "tsx") (web-mode . "jsx")))
    (pcase-let ((`(,mode . ,extension) configuration))
      (dolist (fixture emmet2-test-host-cases)
	(pcase-let ((`(,name ,source ,language ,abbreviation . ,options) fixture))
          (ert-info ((format "%s %s %s" mode extension name))
            (with-temp-buffer
              (setq buffer-file-name (concat "/tmp/emmet2-contract." extension))
              (insert source)
              (goto-char (point-min)) (search-forward "│") (delete-char -1)
              (let ((position (point)))
		(funcall mode)
		(goto-char position)
		(let* ((original (buffer-string))
                       (result (progn (emmet2-context-js-prepare)
                               (emmet2-context-analyze (not (memq 'manual options))))))
                  (should (equal (plist-get result :lang) language))
                  (should (equal (plist-get result :abbr) abbreviation))
                  (should (equal (buffer-string) original))
                  (should (= (point) position))
                  (should (= (length (emmet2-context-js--parsers)) 2))
                  (emmet2-context-stop)
                  (should-not (emmet2-context-js--parsers)))))))))))

(ert-deftest emmet2-contract-host-script-owners ()
  (dolist (mode '(js-mode js-ts-mode typescript-ts-mode web-mode))
    (dolist (case '(("StyleSheet.create" "p[1px 2px]") ("createTheme" "p[1px 2px]")
                    ("ordinary" "p[1px 2px]") ("StyleSheet.create" "m10+p.5")
                    ("createTheme" "m10+p.5") ("ordinary" "m10+p.5")))
      (let ((call (car case)) (abbreviation (cadr case)))
      (ert-info ((format "%s %s" mode call))
        (with-temp-buffer
          (setq buffer-file-name "/tmp/emmet2-contract.html")
          (when (eq mode 'web-mode) (insert "<script>\n"))
          (insert (format "const s = %s({x: {%s}});" call abbreviation))
          (when (eq mode 'web-mode) (insert "\n</script>"))
          (funcall mode)
          (goto-char (point-min))
          (search-forward (if (equal abbreviation "p[1px 2px]") "1px" abbreviation))
          (let ((result (progn (emmet2-context-js-prepare) (emmet2-context-analyze t))))
            (if (equal call "ordinary")
                (should-not result)
              (should (eq (plist-get result :lang) 'css-in-js))
              (should (equal (plist-get result :abbr) abbreviation))))))))))

(provide 'emmet2-host-contract-test)
;;; emmet2-host-contract-test.el ends here
