;;; emmet2-context-lexical-test.el --- CSS and web context contracts -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'emmet2-context)
(require 'web-mode)

;; All 38 planning probes are assertions; full real-point extraction is tested
;; separately below so supplied abbreviation bounds cannot hide scanner bugs.

(defconst emmet2-test-css-position-cases
  '((".card at top level"            ".a { color: red; }\n⟨.card\n"                     css-mode  (css . selector))
             ("@md at top level"              ".a { }\n⟨@md\n"                                    css-mode  (css . selector))
             ("after {"                       ".a {\n  ⟨posa\n}\n"                               css-mode  (css . declaration-start))
             ("after ;"                       ".a {\n  color: red;\n  ⟨posa\n}\n"                css-mode  (css . declaration-start))
             ("same line after ;"             ".a { color: red; ⟨posa }\n"                       css-mode  (css . declaration-start))
             ("value"                         ".a {\n  color: ⟨re\n}\n"                          css-mode  (css . value))
             ("value continuation line"       ".a {\n  margin: 0\n  ⟨au\n}\n"                    css-mode  (css . value))
             ("inside parens"                 ".a { color: rgba(⟨ }\n"                           css-mode  (css . paren-args))
             ("inside raw-value brackets"     ".a {\n  p[1px ⟨]\n}\n"                            css-mode  (css . brackets))
             ("comment"                       ".a { /* ⟨posa */ }\n"                             css-mode  (css . comment))
             ("string"                        ".a { content: \"⟨po\" }\n"                        css-mode  (css . string))
             ("scss nested selector"          ".a {\n  color: red;\n  ⟨&:hv\n}\n"                scss-mode (css . declaration-start))
             ("scss after nested block"       ".a {\n  &:hover { color: red; }\n  ⟨posa\n}\n"    scss-mode (css . declaration-start))
             ("scss @include prelude"         ".a {\n  @include ⟨mi\n}\n"                        scss-mode (css . at-rule-prelude))
             ("scss @in at line start"        ".a {\n  ⟨@in\n}\n"                                scss-mode (css . declaration-start))
             ("@media ( prelude"              "@media (⟨\n"                                      css-mode  (css . paren-args))
             ("@media scr prelude"            "@media ⟨scr\n"                                    css-mode  (css . at-rule-prelude))))

(defconst emmet2-test-web-position-cases
  '(("text content"                  "<div>\n  <p>⟨ul>li*3</p>\n</div>\n"               web-mode (markup))
             ("bare text line"                "<div>\n  ⟨ul>li*3\n</div>\n"                      web-mode (markup))
             ("attribute name <div cl|"       "<div ⟨cl>x</div>\n"                               web-mode (none))
             ("class value"                   "<div class=\"⟨x\">y</div>\n"                      web-mode (none))
             ("style value"                   "<div style=\"⟨c\">y</div>\n"                      web-mode (css . declaration-start))
             ("style value, another style attr later on the line" "<div style=\"⟨c\"></div><div style=\"m\"></div>\n" web-mode (css . declaration-start))
             ("style value, single quotes"    "<div style='⟨m10'></div>\n"                       web-mode (css . declaration-start))
             ("style value after ;"           "<div style=\"color: red; ⟨m\">x</div>\n"          web-mode (css . declaration-start))
             ("style value position"          "<div style=\"color: ⟨re\">x</div>\n"              web-mode (css . value))
             ("<style> declaration-start"     "<style>\n.a {\n  ⟨posa\n}\n</style>\n"            web-mode (css . declaration-start))
             ("<style> selector"              "<style>\n.a { color: red; }\n⟨.b\n</style>\n"      web-mode (css . selector))
             ("<style> value"                 "<style>\n.a { color: ⟨re }\n</style>\n"            web-mode (css . value))
             ("<style> comment"               "<style>\n/* ⟨posa */\n</style>\n"                  web-mode (none))
             ("<style> brace inside comment before" "<style>\n/* { */\n.a {\n  ⟨posa\n}\n</style>\n" web-mode (css . declaration-start))
             ("<style> brace inside string before"  "<style>\n.a { content: \"{\"; ⟨posa }\n</style>\n" web-mode (css . declaration-start))
             ("<script>"                      "<script>\n  ⟨ul>li\n</script>\n"                  web-mode (none))
             ("html comment"                  "<!-- ⟨ul>li -->\n"                                web-mode (none))
             ("apostrophe earlier in text"    "<p>don't</p>\n<p>⟨ul>li</p>\n"                    web-mode (markup))
             ("astro text"                    "---\nconst a = 1;\n---\n<main>\n  ⟨ul>li\n</main>\n" web-mode (markup) "astro")
             ("svelte text"                   "<script>let a = 1;</script>\n<main>\n  ⟨ul>li\n</main>\n" web-mode (markup) "svelte")
             ("astro {expr} (known limitation: not marked by web-mode)" "---\n---\n<main>{items.⟨ma}</main>\n" web-mode (markup) "astro")))

(ert-deftest emmet2-context-css-position-prototypes ()
  (dolist (fixture emmet2-test-css-position-cases)
    (pcase-let ((`(,name ,source ,mode ,expected) fixture))
      (ert-info (name)
        (with-temp-buffer
          (insert source) (funcall mode)
          (goto-char (point-min)) (search-forward "⟨") (delete-char -1)
          (should (equal (cons 'css (emmet2-context--css-position
                                    (point-min) (point) nil (save-excursion (syntax-ppss))))
                         expected)))))))

(ert-deftest emmet2-context-web-position-prototypes ()
  (dolist (fixture emmet2-test-web-position-cases)
    (pcase-let ((`(,name ,source ,mode ,expected . ,engine) fixture))
      (ert-info (name)
        (with-temp-buffer
          (insert source) (funcall mode)
          (when engine (web-mode-set-engine (car engine)))
          (goto-char (point-min)) (search-forward "⟨") (delete-char -1)
          (emmet2-context--js-region)
          (let* ((region (emmet2-context--web-region))
                 (position (when (eq (car region) 'css)
                             (emmet2-context--css-position
                              (nth 1 region) (point) (nth 3 region)
                              (save-excursion
                                (with-syntax-table css-mode-syntax-table
                                  (parse-partial-sexp (nth 1 region) (point)))))))
                 (result (cond ((or (not region) (memq position '(string comment))) '(none))
                               ((eq (car region) 'markup) '(markup))
                               (t (cons 'css position)))))
            (should (equal result expected))))))))

(defconst emmet2-test-lexical-cases
  '((css-mode ".a{m1│0}" css "m10" declaration-start t)
    (css-mode ".a{p(calc(1 + 2)│}" css "p(calc(1 + 2)" declaration-start t)
    (css-mode ".a{p[1px│}" css "p[1px" declaration-start t)
    (css-mode ".a{--v[{a:1}│]}" css "--v[{a:1}]" declaration-start t)
    (css-mode ".a { color: red; p[1px│ 2px] }" css "p[1px 2px]" declaration-start t)
    (css-mode ".a { content: ct['a│ b'] }" css "ct['a b']" value nil)
    (css-mode ".a { color: re│ }" css "re" value nil)
    (css-mode ".a{display:fl│}" css "display:fl" value nil)
    (css-mode ".a{dis│play:flex}" css "display:flex" value nil)
    (css-mode ".a{display:│}" css "display:" value nil)
    (css-mode ".a{--accent:re│}" css "--accent:re" value nil)
    (css-mode ".a{future-prop:foo│}" css "future-prop:foo" value nil)
    (scss-mode ".a{$accent:re│}" css "$accent:re" value nil)
    (css-mode ".a{d:n│}" css "d:n" value nil)
    (css-mode ".a{_:hv│}" css "_:hv" declaration-start t)
    (css-mode ".a{button::be│}" css "button::be" declaration-start t)
    (css-mode ".a {\n margin: 0\n au│\n}" css "au" value nil)
    (css-mode "@media scr│" css "scr" at-rule-prelude nil)
    (css-mode ".card│" css ".card" selector nil)
    (css-mode "@md│" css "@md" selector t)
    (css-mode ":not(.a,.b│)" css ":not(.a,.b)" selector t)
    (css-mode "_hv│" css "_hv" selector t)
    (css-mode ".a{/*m10│*/}" nil nil nil nil)
    (css-mode ".a{content:'m10│'}" nil nil nil nil)
    (scss-mode ".a { &:hover { color: red; } m10│ }" css "m10" declaration-start t)
    (scss-mode ".a { @include mi│ }" css "mi" at-rule-prelude nil)
    (scss-mode ".a { @include mixin; m10│ }" css "m10" declaration-start t)
    (css-mode "@media screen { .a { m10│ } }" css "m10" declaration-start t)
    (css-mode ".a {\n  /* Layout */\n  m10│\n}" css "m10" declaration-start t)
    (css-mode ".a { color: red; /* @see x */ m10│ }" css "m10" declaration-start t)
    (css-mode ".a{/* note */m10│}" css "m10" declaration-start t)
    (css-mode ".a{color:red;/* note */m10│}" css "m10" declaration-start t)
    (css-mode ".a{/* note\n continued */m10│}" css "m10" declaration-start t)
    (css-mode ".a{/* m10│ */p10}" nil nil nil nil)
    (css-mode ".a{ct['/* literal */']│}" css "ct['/* literal */']" declaration-start t)
    (css-mode ".a {\r\n  m10│\r\n}" css "m10" declaration-start t)
    (scss-mode ".a {\n  // note\n  m10│\n}" css "m10" declaration-start t)
    (scss-mode ".a {\n//\nm10│\n}" css "m10" declaration-start t)
    (scss-mode ".a {\n//  \n//\nm10│\n}" css "m10" declaration-start t)
    (scss-mode ".a { color:\n//\nm10│\n}" css "m10" value nil)
    (web-mode "<style lang='scss'>.a {\n//\nm10│\n}</style>" css "m10" declaration-start t)
    (web-mode "<style lang='less'>.a {\n//  \nm10│\n}</style>" css "m10" declaration-start t)
    (web-mode "<style lang=\"scss\">\n// Don't touch\n.a {\n  m10│\n}\n</style>" css "m10" declaration-start t)
    (web-mode "<style lang=\"scss\">.a {\n  // color: red; m10│\n}</style>" nil nil nil nil)
    (web-mode "<style lang='scss'>.a{/* one\n two */m10│}</style>" css "m10" declaration-start t)
    (web-mode "<style lang='scss'>.a{/* one\n ;m10│\n*/}</style>" nil nil nil nil)
    (web-mode "<style lang='less'>.a{/* one\n ;m10│\n*/}</style>" nil nil nil nil)
    (web-mode "<p>ul>│li*3</p>" markup "ul>li*3" markup t)
    (web-mode "<p>│ul>li</p><b>other</b>" markup "ul>li" markup t)
    (web-mode "<div cl│>x</div>" nil nil nil nil)
    (web-mode "<div class='m10│'>x</div>" nil nil nil nil)
    (web-mode "<div style='m1│0'>x</div><div style='p10'></div>" css "m10" declaration-start t)
    (web-mode "<div style='color: red; p[1px│ 2px]'>x</div>" css "p[1px 2px]" declaration-start t)
    (web-mode "<div style='color: re│'>x</div>" css "re" value nil)
    (web-mode "<div style='display:fl│'></div>" css "display:fl" value nil)
    (web-mode "<style>.a{display:fl│}</style>" css "display:fl" value nil)
    (web-mode "<div style=\"ct['hi│']\">x</div>" css "ct['hi']" declaration-start t)
    ;; web-mode drops the value's attribute markers for this unfinished tag.
    (web-mode "<div style=\"m10│" nil nil nil nil)
    (web-mode "<style>.a{m1│0}</style>" css "m10" declaration-start t)
    (web-mode "<style>.a{/* note */m10│}</style>" css "m10" declaration-start t)
    (web-mode "<div style='/* note */m10│'></div>" css "m10" declaration-start t)
    (web-mode "<style>│@md</style>" css "@md" selector t)
    (web-mode "<style>@md│</style>" css "@md" selector t)
    (web-mode "<style>│.card</style>" css ".card" selector nil)
    (web-mode "<style>/* { */ .a{content:'{';m10│}</style>" css "m10" declaration-start t)
    (web-mode "<style>.a {color: re│}</style>" css "re" value nil)
    (web-mode "<style>/*m10│*/</style>" nil nil nil nil)
    (web-mode "<!--ul>li│-->" nil nil nil nil)
    (fundamental-mode "ul>li│" markup "ul>li" markup nil)
    (html-mode "ul>li│" markup "ul>li" markup nil)
    (html-mode "<p>ul>li│</p>" markup "ul>li" markup nil)
    (fundamental-mode "()│" nil nil nil nil)))

(ert-deftest emmet2-context-lexical-real-point ()
  (dolist (fixture emmet2-test-lexical-cases)
    (pcase-let ((`(,mode ,source ,language ,abbreviation ,position ,auto) fixture))
      (ert-info ((format "%s %s" mode source))
        (with-temp-buffer
          (insert source) (funcall mode)
          (goto-char (point-min)) (search-forward "│") (delete-char -1)
          (let* ((point-before (point)) (original (buffer-substring-no-properties (point-min) (point-max)))
                 (result (emmet2-context-analyze)))
            (should (equal (plist-get result :lang) language))
            (should (equal (plist-get result :abbr) abbreviation))
            (should (equal (plist-get result :position) position))
            (should (equal (emmet2-context-analyze t) (when auto result)))
            (should (equal (buffer-substring-no-properties (point-min) (point-max)) original))
            (should (= (point) point-before))
            (should-not (emmet2-context--parsers))))))))

(ert-deftest emmet2-context-web-engine-blocks-bound-markup ()
  (dolist (case '(("django" "<div>{% if x %}ul>li│{% endif %}</div>" "ul>li")
                  ("django" "<div>{{ x }}ul>li│</div>" "ul>li")
                  ("django" "<div>span│{{ msg }}</div>" "span")
                  ("django" "<div>{{ ul>li│ }}</div>" nil)
                  ("svelte" "{#if x}ul>li│{/if}" "ul>li")
                  ("vue" "<div>span│{{ msg }}</div>" "span")))
    (ert-info ((format "%S" case))
      (with-temp-buffer
        (insert (nth 1 case)) (web-mode) (web-mode-set-engine (car case))
        (goto-char (point-min)) (search-forward "│") (delete-char -1)
        (should (equal (plist-get (emmet2-context-analyze) :abbr) (nth 2 case)))
        (should (equal (plist-get (emmet2-context-analyze t) :abbr) (nth 2 case)))))))

(ert-deftest emmet2-context-web-style-language-uses-real-attribute ()
  (dolist (case '(("lang=\n\"scss\"" scss)
                  ("LANG='SCSS'" scss)
                  ("lang=scss" scss)
                  ("data-lang=\"scss\"" css)
                  ("title=\"lang='scss'\"" css)
                  ("lang=\"scss\" data-lang=\"css\"" scss)
                  ("title='<style>' lang='scss'" scss)
                  ("lang='scss-extra'" css)
                  ("lang='less'" css)))
    (ert-info ((car case))
      (with-temp-buffer
        (insert "<style\n " (car case) ">@us│</style>")
        (web-mode) (search-backward "│") (delete-char 1)
        (let ((source (buffer-string)) (position (point)))
          (should (eq (plist-get (emmet2-context-analyze) :syntax) (cadr case)))
          (should (eq (plist-get (emmet2-context-analyze t) :syntax) (cadr case)))
          (should (equal source (buffer-string)))
          (should (= position (point))))))))

(ert-deftest emmet2-context-html-css-need-no-tree-sitter ()
  (cl-letf (((symbol-function 'treesit-available-p) (lambda () nil))
            ((symbol-function 'treesit-language-available-p) (lambda (&rest _) nil)))
    (dolist (fixture '((css-mode ".a { m10 }") (web-mode "<div style='m10'></div>")))
      (with-temp-buffer
        (insert (cadr fixture)) (funcall (car fixture))
        (goto-char (point-min)) (search-forward "m10")
        (should (eq (plist-get (emmet2-context-analyze t) :lang) 'css))))))

(ert-deftest emmet2-context-web-pending-scan-and-part-switch ()
  (with-temp-buffer
    (insert "<style>.a{m10}</style><p>ul>li</p><style>.b{p10}</style>")
    (web-mode)
    (goto-char (point-min)) (search-forward "m10")
    (should (equal (plist-get (emmet2-context-analyze t) :abbr) "m10"))
    (search-forward "ul>li")
    (should (eq (plist-get (emmet2-context-analyze t) :lang) 'markup))
    (search-forward "p10")
    (insert "+m5")
    (should web-mode-change-beg)
    (should (equal (plist-get (emmet2-context-analyze t) :abbr) "p10+m5"))
    (should-not web-mode-change-beg)
    (goto-char (point-min)) (search-forward "m10")
    (delete-char -3) (insert "c")
    (should (equal (plist-get (emmet2-context-analyze t) :abbr) "c"))
    (should-not (emmet2-context--parsers))))

(ert-deftest emmet2-context-web-narrowing-keeps-host-and-visible-boundaries ()
  (dolist (source '("<style>.a{m10}</style>" "<div style=\"m10\"></div>"
                     "<script>const s = createTheme({x: {m10}});</script>"))
    (with-temp-buffer
      (setq buffer-file-name "/tmp/emmet2-narrow.html")
      (insert source) (web-mode)
      (goto-char (point-min)) (search-forward "m10")
      (let ((start (- (point) 3)) (end (point)))
        (narrow-to-region start end)
        (emmet2-context--prepare)
        (dolist (automatic '(nil t))
          (should (equal (plist-get (emmet2-context-analyze automatic) :abbr) "m10"))
          (should (= (point-min) start))
          (should (= (point-max) end))
          (should (= (point) end)))
        (narrow-to-region (1+ start) end)
        (should-not (emmet2-context-analyze))
        (should-not (emmet2-context-analyze t))))))

(defmacro emmet2-test-with-web-insertion (source &rest body)
  "Run BODY after scanning SOURCE with point at its vertical-bar marker."
  (declare (indent 1) (debug t))
  `(with-temp-buffer
     (insert ,source)
     (goto-char (point-min)) (search-forward "│") (delete-char -1)
     (let ((position (point)))
       (setq buffer-file-name "/tmp/emmet2-insertion.html")
       (web-mode) (goto-char position))
     (emmet2-context-analyze)
     ,@body))

(ert-deftest emmet2-context-web-insertion-matches-full-scan ()
  (dolist (source '("<p>before</p><style>.a { m10│ }</style><p>after</p>"
                     "<style>@media screen { .a { m10│ } }</style>"
                     "<style>.a { content: '👋{'; m10│ }</style>"
                     "<style>.a { /* } */ m10│ }</style>"
                     "<style>.a { content: 'm10│'; }</style>"
                     "<style>.a { /* m10│ */ }</style>"))
    (ert-info (source)
      (emmet2-test-with-web-insertion source
        (insert "1")
        (let* ((owner (emmet2-context--owner))
               (entry (emmet2-context--state-web-insertion owner)))
          (should entry)
          (let ((result (emmet2-context-analyze t)) (position (point))
                (optimized (buffer-string)))
            (should-not web-mode-change-beg)
            (should-not web-mode-change-end)
            (should-not (emmet2-context--state-web-insertion owner))
            (should-not (marker-buffer (nth 2 entry)))
            (web-mode-buffer-scan)
            (should (equal-including-properties optimized (buffer-string)))
            (should (equal result (emmet2-context-analyze t)))
            (should (= position (point)))))))))

(ert-deftest emmet2-context-web-insertion-unsafe-edits-use-normal-scan ()
  (dolist (edit '(structural paste replace delete repeated))
    (emmet2-test-with-web-insertion "<style>.a { m10│ }</style><p>after</p>"
      (pcase edit
        ('structural (insert "</style><p>"))
        ('paste (insert "12"))
        ('replace (delete-char -1) (insert "1"))
        ('delete (delete-char -1))
        ('repeated (insert "1") (insert "2")))
      (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))
      (let ((result (emmet2-context-analyze)) (optimized (buffer-string)))
        (web-mode-buffer-scan)
        (should (equal-including-properties optimized (buffer-string)))
        (should (equal result (emmet2-context-analyze))))))
  ;; An ordinary character can complete an HTML terminator already in CSS.
  (emmet2-test-with-web-insertion "<style>.a { </styl│> }</style><p>after</p>"
    (insert "e")
    (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))
    (let ((result (emmet2-context-analyze)) (scanned (buffer-string)))
      (web-mode-buffer-scan)
      (should (equal-including-properties scanned (buffer-string)))
      (should (equal result (emmet2-context-analyze))))))

(ert-deftest emmet2-context-web-insertion-narrowing-and-error-cleanup ()
  (emmet2-test-with-web-insertion "<style>.a { m10│ }</style>"
    (let ((start (- (point) 3)))
      (narrow-to-region start (point))
      (insert "1")
      (let* ((owner (emmet2-context--owner)) (entry (emmet2-context--state-web-insertion owner))
             (beg web-mode-change-beg) (end web-mode-change-end) (position (point)))
        (should entry)
        (cl-letf (((symbol-function 'web-mode-scan-region) (lambda (&rest _) (error "scan failed"))))
          (should-error (emmet2-context-analyze)))
        (should (equal (list web-mode-change-beg web-mode-change-end) (list beg end)))
        (should-not (marker-buffer (nth 2 entry)))
        (should (= start (point-min)))
        (should (= position (point-max)))
        (should (= position (point)))
        (should (equal (plist-get (emmet2-context-analyze t) :abbr) "m101"))))))

(ert-deftest emmet2-context-web-insertion-unobserved-edits-and-stop ()
  (dolist (action '(inhibited indirect stop major-mode))
    (emmet2-test-with-web-insertion "<style>.a { m10│ }</style><p>other</p>"
      (insert "1")
      (let* ((owner (emmet2-context--owner)) (entry (emmet2-context--state-web-insertion owner)))
        (should entry)
        (pcase action
          ('inhibited (let ((inhibit-modification-hooks t)) (insert "2")))
          ('indirect
           (let ((view (clone-indirect-buffer " *emmet2-css-view*" nil)))
             (unwind-protect (with-current-buffer view (insert "2")) (kill-buffer view))))
          ('stop (emmet2-context-stop))
          ('major-mode (fundamental-mode)))
        (when (memq action '(inhibited indirect))
          (emmet2-context-analyze)
          (should-not (emmet2-context--state-web-insertion owner)))
        (should-not (marker-buffer (nth 2 entry)))
        (should-not (marker-buffer (nth 3 entry)))))))

(ert-deftest emmet2-context-web-insertion-cannot-reuse-stale-part-evidence ()
  (emmet2-test-with-web-insertion "<style>.a { m10│ }</style><p>other</p>"
    (let ((inhibit-modification-hooks t))
      (save-excursion
        (goto-char (point-min)) (search-forward "style")
        (replace-match "script")
        (search-forward "</style>") (replace-match "</script>")))
    (insert "1")
    (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))
    (should-not (emmet2-context-analyze)))
  (emmet2-test-with-web-insertion "<style>.a { m10│ }</style><p>other</p><style>.b { p5 }</style>"
    (insert "1")
    (search-forward "p5") (insert "1")
    (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))
    (should (equal (plist-get (emmet2-context-analyze) :abbr) "p51"))
    (let ((optimized (buffer-string)))
      (web-mode-buffer-scan)
      (should (equal-including-properties optimized (buffer-string))))))

(ert-deftest emmet2-context-web-insertion-configuration-change-invalidates ()
  (dolist (setting '(engine content-type))
    (emmet2-test-with-web-insertion "<style>.a { m10│ }</style>"
      (insert "1")
      (should (emmet2-context--state-web-insertion (emmet2-context--owner)))
      (if (eq setting 'engine) (setq web-mode-engine "php") (setq web-mode-content-type "css"))
      (let ((scan (symbol-function 'web-mode-scan)) (calls 0))
        (cl-letf (((symbol-function 'web-mode-scan)
                   (lambda (&rest args) (cl-incf calls) (apply scan args))))
          (emmet2-context-analyze))
        (should (= calls 1))
        (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))))))

(ert-deftest emmet2-context-web-insertion-nested-hook-edit-invalidates ()
  (emmet2-test-with-web-insertion "<style>.a { m10│ }</style>"
    (let ((hook (lambda (_beg end _length)
                  (let ((inhibit-modification-hooks t))
                    (save-excursion (goto-char end) (insert "</style><p>"))))))
      (add-hook 'after-change-functions hook nil t)
      (unwind-protect (insert "1") (remove-hook 'after-change-functions hook t)))
    (should-not (emmet2-context--state-web-insertion (emmet2-context--owner)))
    (emmet2-context-analyze)
    (let ((scanned (buffer-string)))
      (web-mode-buffer-scan)
      (should (equal-including-properties scanned (buffer-string))))))

(ert-deftest emmet2-context-web-insertion-partial-scan-error-recovers ()
  (emmet2-test-with-web-insertion "<style>.a { content: '{{'; m10│ }</style>"
    (insert "1")
    (cl-letf (((symbol-function 'web-mode-scan-region)
               (lambda (beg end &rest _)
                 (with-silent-modifications
                   (remove-list-of-text-properties beg end '(part-token syntax-table)))
                 (error "partial scan"))))
      (should-error (emmet2-context-analyze)))
    (should (equal (plist-get (emmet2-context-analyze t) :abbr) "m101"))
    (let ((recovered (buffer-string)))
      (web-mode-buffer-scan)
      (should (equal-including-properties recovered (buffer-string))))))

(provide 'emmet2-context-lexical-test)
;;; emmet2-context-lexical-test.el ends here
